-- 0410_conversation_intelligence: AI conversation intelligence
-- (spec 37-ai-conversation-intelligence, P0).
--
-- TWO tables, one job each:
--
--   conversation_analyses  one AI reading of one conversation: a summary, a
--                          sentiment signal, extracted action items or the
--                          key topics. Stored with FULL ATTRIBUTION —
--                          provider, model, run id, tokens, latency and the
--                          exact number of source characters that were sent.
--   call_transcripts       the text of a call or meeting, INGESTED not
--                          produced. See "the speech-to-text seam" below.
--
-- POLYMORPHIC SUBJECT, NO FOREIGN KEY
-- -----------------------------------
-- `subject_type` + `subject_id` name the conversation being analysed. The
-- conversations live in modules this one does not own (email threads,
-- WhatsApp conversations, calls), so `subject_id` is a PLAIN uuid with an
-- index and NO foreign key — the same rule `people.company_id`
-- (0010_people.sql) and `ai_runs.actor_id` (0340_ai.sql) follow. The domain
-- service resolves a subject through the OWNING module's service, which is
-- also what makes permission inheritance real rather than declared.
--
-- PERMISSION INHERITANCE IS NOT A COLUMN
-- --------------------------------------
-- There is deliberately no `visible_to` / `owner_id` on an analysis. An
-- analysis is readable exactly when its SUBJECT is readable, re-resolved on
-- every read through the source module's service. Copying the source's
-- visibility into a column here would let the copy go stale the moment the
-- thread is reassigned.
--
-- WHY tokens LIVE HERE AND NOT IN ai_runs
-- ---------------------------------------
-- `ai_runs.conversation_id` is NOT NULL and references `ai_conversations` —
-- an assistant chat thread, which an analysis does not have. So an analysis
-- records its own accounting on its own row and shares the vocabulary
-- (`run_id`, `prompt_tokens`, `completion_tokens`, `total_tokens`,
-- `latency_ms`) so spec 38's usage rollups can UNION the two. `run_id` is a
-- plain uuid: it is generated by this module, is the id every audit row for
-- the analysis carries, and points at no table.
--
-- BOUNDED COST IS RECORDED, NOT ASSUMED
-- -------------------------------------
-- Conversation text is unbounded; tokens are not free. The service truncates
-- deterministically to a documented cap before the provider is called, and
-- `source_chars` / `analysed_chars` / `truncated` record exactly what
-- happened, so an unbounded request would be visible in the data rather than
-- only on an invoice.
--
-- NEVER STORED HERE
-- -----------------
-- No prompt text, no transcript excerpt and no provider error body.
-- `conversation_analyses.output` holds the MODEL'S STRUCTURED ANSWER only
-- (a summary the user asked for), never the source conversation. Failures
-- record `error_code` plus a message that has already had every run of
-- source text removed (`redactConversationContent`). Audit rows for this
-- module carry metadata only — subject, type, model, run id, outcome.
--
-- THE SPEECH-TO-TEXT SEAM
-- -----------------------
-- `call_transcripts` is an INGESTION table. This module does no audio
-- processing: speech-to-text needs an audio pipeline and a transcription
-- dependency that cannot be added here. A transcript arrives either from a
-- provider/notetaker payload (`source = 'provider'`, `provider_id` names it,
-- `external_id` makes re-delivery idempotent) or from a human paste
-- (`source = 'manual'`). When an STT provider is wired it writes rows here
-- through the same ingest path and nothing downstream changes.
--
-- Down migration:
--   DROP TABLE call_transcripts; DROP TABLE conversation_analyses;

CREATE TABLE IF NOT EXISTS conversation_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID,
  updated_by UUID,
  deleted_at TIMESTAMPTZ,
  workspace_id UUID NOT NULL,
  -- The conversation this reads. Plain uuid, NO foreign key (see header).
  subject_type VARCHAR(32) NOT NULL,
  subject_id UUID NOT NULL,
  analysis_type VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'queued',
  -- Attribution (spec 37 §14). NULL until the run completes.
  provider_id VARCHAR(64),
  model VARCHAR(128),
  -- This module's own run id. Plain uuid; carried by every audit row.
  run_id UUID,
  -- The model's structured answer. Never the source conversation.
  output JSONB,
  prompt_tokens INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  -- Cost control, recorded per analysis (see header).
  source_chars INTEGER NOT NULL DEFAULT 0,
  analysed_chars INTEGER NOT NULL DEFAULT 0,
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  -- users.id of whoever asked. Plain uuid, NO foreign key.
  requested_by UUID,
  analysed_at TIMESTAMPTZ,
  error_code VARCHAR(64),
  -- Already redacted of all source text before it reaches this column.
  error_message VARCHAR(500),
  correlation_id VARCHAR(128),
  CONSTRAINT conversation_analyses_subject_type_chk
    CHECK (subject_type IN ('email_thread', 'whatsapp_conversation', 'call')),
  CONSTRAINT conversation_analyses_type_chk
    CHECK (analysis_type IN ('summary', 'sentiment', 'action_items', 'key_topics')),
  CONSTRAINT conversation_analyses_status_chk
    CHECK (status IN ('queued', 'succeeded', 'failed'))
);

CREATE INDEX IF NOT EXISTS conversation_analyses_workspace_idx
  ON conversation_analyses (workspace_id);
-- The detail query: every analysis of one conversation, newest first.
CREATE INDEX IF NOT EXISTS conversation_analyses_subject_idx
  ON conversation_analyses (workspace_id, subject_type, subject_id, created_at);
-- The list query: filter by kind of analysis / by state.
CREATE INDEX IF NOT EXISTS conversation_analyses_type_idx
  ON conversation_analyses (workspace_id, analysis_type, created_at);
CREATE INDEX IF NOT EXISTS conversation_analyses_status_idx
  ON conversation_analyses (workspace_id, status, created_at);
CREATE INDEX IF NOT EXISTS conversation_analyses_run_idx
  ON conversation_analyses (run_id);

CREATE TABLE IF NOT EXISTS call_transcripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID,
  updated_by UUID,
  deleted_at TIMESTAMPTZ,
  workspace_id UUID NOT NULL,
  -- Same polymorphic pair as above. Plain uuid, NO foreign key.
  subject_type VARCHAR(32) NOT NULL DEFAULT 'call',
  subject_id UUID NOT NULL,
  -- 'provider' (notetaker / STT payload) or 'manual' (pasted by a human).
  source VARCHAR(16) NOT NULL,
  -- Which notetaker/STT provider produced it. NULL for a manual paste.
  provider_id VARCHAR(64),
  -- Provider-side transcript id. Unique per workspace: re-delivery is a
  -- no-op instead of a duplicate transcript (spec 01 idempotency).
  external_id VARCHAR(255),
  language VARCHAR(16),
  text TEXT NOT NULL,
  -- [{ speaker, startMs, endMs, text }] — speaker identification as the
  -- provider reported it. This module never infers speakers from audio.
  segments JSONB,
  duration_ms INTEGER,
  speaker_count INTEGER NOT NULL DEFAULT 0,
  char_count INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT call_transcripts_subject_type_chk
    CHECK (subject_type IN ('email_thread', 'whatsapp_conversation', 'call')),
  CONSTRAINT call_transcripts_source_chk
    CHECK (source IN ('provider', 'manual'))
);

CREATE INDEX IF NOT EXISTS call_transcripts_workspace_idx
  ON call_transcripts (workspace_id);
CREATE INDEX IF NOT EXISTS call_transcripts_subject_idx
  ON call_transcripts (workspace_id, subject_type, subject_id, created_at);
-- Idempotent provider re-delivery. Partial: manual pastes have no id.
CREATE UNIQUE INDEX IF NOT EXISTS call_transcripts_external_idx
  ON call_transcripts (workspace_id, external_id)
  WHERE external_id IS NOT NULL AND deleted_at IS NULL;

COMMENT ON TABLE conversation_analyses IS
  'One AI reading of one conversation (spec 37): summary, sentiment, action items or key topics, with provider/model/run/token attribution. Readable exactly when its subject is.';
COMMENT ON COLUMN conversation_analyses.subject_id IS
  'Email thread / WhatsApp conversation / call id. Plain uuid, no FK: this module does not own those tables.';
COMMENT ON COLUMN conversation_analyses.output IS
  'The model structured answer only. Never contains the source conversation text.';
COMMENT ON COLUMN conversation_analyses.analysed_chars IS
  'Characters actually sent to the provider after deterministic truncation. truncated = TRUE when source_chars exceeded the cap.';
COMMENT ON COLUMN conversation_analyses.error_message IS
  'Provider failure with every run of source text removed. Never contains transcript content.';
COMMENT ON TABLE call_transcripts IS
  'Ingested call/meeting transcript (spec 37): text plus provider-reported speaker segments. This module does NO audio processing — speech-to-text writes rows here through the ingest path.';
COMMENT ON COLUMN call_transcripts.external_id IS
  'Provider transcript id. Unique per workspace so webhook re-delivery is idempotent.';
