export {
  createAiAgentService,
  subscribeAiAgentDispatcher,
  aiAgentRunCorrelationId,
  aiAgentToolNames,
  buildAiAgentSystemPrompt,
  buildAiAgentTaskMessage,
  matchesAiAgentTrigger,
  parseAiAgentRunCorrelationId,
  AiAgentNotFoundError,
  AiAgentRunNotFoundError,
  AiAgentStateError,
  AiAgentUnknownToolError,
  AI_AGENT_RUN_CORRELATION_PREFIX,
  AI_AGENT_SERVICE_METHODS,
  AI_AGENT_TERMINAL_RUN_STATUSES,
} from "./service"
export type { AiAgentService } from "./service"
export {
  assertAiAgentActorResolved,
  assertAiAgentRunAllowed,
  assertMayAssignAiAgentOwner,
  aiAgentPermission,
  AI_AGENT_OBJECT,
  AI_AGENT_RUN_OBJECT,
  AI_AGENT_TOOL_OBJECT,
} from "./access"
export {
  assertAiAgentToolAccess,
  createAiAgentProposalTool,
  createAiAgentToolRegistry,
  toAiAgentReadTool,
  AiAgentWriteToolNotAllowedError,
  AI_AGENT_TOOL_PROPOSE,
} from "./tools"
export {
  aiAgentProposeToolArgsSchema,
  aiAgentQuerySchema,
  aiAgentRunQuerySchema,
  aiAgentRunSchema,
  aiAgentRunStatusSchema,
  aiAgentSchema,
  aiAgentStatusSchema,
  aiAgentTriggerEventSchema,
  aiAgentTriggerTypeSchema,
  clampAiAgentBudget,
  createAiAgentSchema,
  isAiAgentTriggerEvent,
  runAiAgentSchema,
  setAiAgentStatusSchema,
  updateAiAgentSchema,
  AI_AGENT_DEFAULT_MAX_STEPS,
  AI_AGENT_DEFAULT_MAX_TOOL_CALLS,
  AI_AGENT_DEFAULT_MAX_TOTAL_TOKENS,
  AI_AGENT_MAX_CASCADE_DEPTH,
  AI_AGENT_MAX_STEPS_CEILING,
  AI_AGENT_MAX_TOOL_CALLS_CEILING,
  AI_AGENT_MAX_TOTAL_TOKENS_CEILING,
  AI_AGENT_RUN_STATUSES,
  AI_AGENT_STATUSES,
  AI_AGENT_TRIGGER_EVENTS,
  AI_AGENT_TRIGGER_TYPES,
} from "./schemas"
export type {
  AiAgentDto,
  AiAgentProposeToolArgs,
  AiAgentQuery,
  AiAgentRunDto,
  AiAgentRunQuery,
  AiAgentRunStatus,
  AiAgentStatus,
  AiAgentTriggerType,
  CreateAiAgentInput,
  RunAiAgentInput,
  SetAiAgentStatusInput,
  UpdateAiAgentInput,
} from "./schemas"
export type {
  AiAgent,
  AiAgentActorRoleResolver,
  AiAgentAuditInput,
  AiAgentDispatchDecision,
  AiAgentDispatchResult,
  AiAgentDispatchSkipReason,
  AiAgentListQuery,
  AiAgentListResult,
  AiAgentRun,
  AiAgentRunJobRequest,
  AiAgentRunListQuery,
  AiAgentRunListResult,
  AiAgentRunOutcome,
  AiAgentRunQueuePort,
  AiAgentServiceContext,
  AiAgentServiceDeps,
  AiAgentStore,
  AiAgentTool,
  AiAgentToolAccess,
  AiAgentToolCallReport,
  AiAgentToolContext,
  AiAgentToolRegistry,
  AiAgentTriggerEnvelope,
  AiAgentWithRuns,
} from "./types"
// Shared across every CRM module — see ../ports.ts for why they live there.
export type { AuditWriter, EventEmitter } from "../ports"
