export {
  createWorkflowAutomationService,
  parseWorkflowRunCorrelationId,
  subscribeWorkflowDispatcher,
  WorkflowActionError,
  WorkflowNotFoundError,
  WorkflowRunNotFoundError,
  workflowRunCorrelationId,
  WORKFLOW_RUN_CORRELATION_PREFIX,
} from "./service"
export type { WorkflowAutomationService } from "./service"
export {
  assertWorkflowActionAllowed,
  assertWorkflowActorResolved,
  workflowActionPermission,
  workflowPermission,
  WORKFLOW_ACTION_PERMISSIONS,
  WORKFLOW_OBJECT,
} from "./access"
export {
  matchesWorkflowConditions,
  matchesWorkflowTrigger,
  renderWorkflowTemplate,
  toWorkflowConditionRecord,
} from "./conditions"
export {
  createWorkflowSchema,
  describeWorkflowCatalogue,
  isWorkflowTriggerEvent,
  runWorkflowSchema,
  updateWorkflowSchema,
  workflowActionSchema,
  workflowAddTagActionSchema,
  workflowCatalogueSchema,
  workflowCreateTaskActionSchema,
  workflowFilterOperators,
  workflowFilterOperatorSchema,
  workflowFilterTreeSchema,
  workflowNotifyActionSchema,
  workflowQuerySchema,
  workflowRunQuerySchema,
  workflowRunSchema,
  workflowRunStepSchema,
  workflowSchema,
  workflowStatusSchema,
  workflowTriggerEventSchema,
  workflowUpdateFieldActionSchema,
  WORKFLOW_ACTION_TYPES,
  WORKFLOW_MAX_ACTIONS,
  WORKFLOW_MAX_CASCADE_DEPTH,
  WORKFLOW_STATUSES,
  WORKFLOW_TARGET_UPDATED_EVENTS,
  WORKFLOW_TRIGGER_EVENTS,
} from "./schemas"
export type {
  CreateWorkflowInput,
  RunWorkflowInput,
  UpdateWorkflowInput,
  WorkflowActionInput,
  WorkflowActionType,
  WorkflowCatalogue,
  WorkflowDto,
  WorkflowFilterOperator,
  WorkflowQuery,
  WorkflowRunDto,
  WorkflowRunQuery,
  WorkflowRunStepDto,
} from "./schemas"
export type {
  WorkflowActionExecutorPort,
  WorkflowActionTarget,
  WorkflowActorRoleResolver,
  WorkflowAuditInput,
  WorkflowAutomationServiceContext,
  WorkflowAutomationServiceDeps,
  WorkflowAutomationStore,
  WorkflowDispatchDecision,
  WorkflowDispatchResult,
  WorkflowDispatchSkipReason,
  WorkflowFilterCondition,
  WorkflowFilterGroup,
  WorkflowFilterNode,
  WorkflowFilterTree,
  WorkflowListQuery,
  WorkflowListResult,
  WorkflowRecord,
  WorkflowRunJobRequest,
  WorkflowRunListQuery,
  WorkflowRunListResult,
  WorkflowRunOutcome,
  WorkflowRunQueuePort,
  WorkflowRunRecord,
  WorkflowRunStepRecord,
  WorkflowRunWithSteps,
  WorkflowTriggerEnvelope,
  WorkflowWithRuns,
} from "./types"
// Shared across every CRM module — see ../ports.ts for why they live there.
export type { AuditWriter, EventEmitter } from "../ports"
