import { isNull } from "drizzle-orm"
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core"
import { baseColumns, workspaceColumn } from "./base"

/**
 * Outbound webhooks + public API keys (spec 32-api-webhooks, P0).
 *
 * Three tables, one responsibility each:
 *
 * - `webhook_subscriptions` — where a workspace wants events POSTed, which
 *   events, and the sealed HMAC signing secret. There is deliberately NO
 *   plaintext secret column (same shape as `integration_credentials`), so
 *   no query, export or log line can leak one.
 * - `webhook_deliveries` — one row per (subscription, event). The UNIQUE
 *   index on that pair IS the no-double-delivery guarantee; every attempt
 *   is appended to `attempts` with its status code, response snippet and
 *   duration.
 * - `api_keys` — SHA-256 hashes of issued keys, plus the workspace and role
 *   the key acts as. The raw key exists only in the create response.
 *
 * Naming: the exported symbols are deliberately distinctive
 * (`webhookSubscriptions`, `webhookDeliveries`, `publicApiKeys`) because the
 * schema barrel is generated by `export *` — `apiKeys` is a name another
 * module could plausibly want, `publicApiKeys` is not.
 */

export const WEBHOOK_DELIVERY_STATUSES = [
  "pending",
  "delivering",
  "succeeded",
  /** Transient failure; `next_attempt_at` holds the backoff deadline. */
  "failed",
  /** Terminal: permanent rejection, or transient past `max_attempts`. */
  "dead_lettered",
] as const

export type WebhookDeliveryStatusValue = (typeof WEBHOOK_DELIVERY_STATUSES)[number]

export function isWebhookDeliveryStatusValue(value: unknown): value is WebhookDeliveryStatusValue {
  return (
    typeof value === "string" && (WEBHOOK_DELIVERY_STATUSES as readonly string[]).includes(value)
  )
}

export const PUBLIC_API_KEY_ROLES = ["owner", "admin", "member", "viewer"] as const

export type PublicApiKeyRoleValue = (typeof PUBLIC_API_KEY_ROLES)[number]

export function isPublicApiKeyRoleValue(value: unknown): value is PublicApiKeyRoleValue {
  return typeof value === "string" && (PUBLIC_API_KEY_ROLES as readonly string[]).includes(value)
}

/** One recorded delivery attempt. Bounded by `max_attempts`. */
export type WebhookDeliveryAttemptRecord = {
  attempt: number
  at: string
  outcome: "succeeded" | "transient" | "permanent"
  statusCode: number | null
  durationMs: number
  /** First 512 characters of the response body. Never a request secret. */
  responseSnippet: string | null
  error: string | null
}

export const webhookSubscriptions = pgTable(
  "webhook_subscriptions",
  {
    ...baseColumns,
    ...workspaceColumn,
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    /** HTTPS only, and re-checked against the SSRF guard before every send. */
    targetUrl: text("target_url").notNull(),
    eventNames: jsonb("event_names").$type<string[]>().notNull().default([]),
    active: boolean("active").notNull().default(true),
    secretAlgorithm: varchar("secret_algorithm", { length: 32 }).notNull().default("aes-256-gcm"),
    /** Key-rotation extension point: re-seal rows with a newer version. */
    secretKeyVersion: varchar("secret_key_version", { length: 16 }).notNull().default("v1"),
    secretCiphertext: text("secret_ciphertext").notNull(),
    secretIv: text("secret_iv").notNull(),
    secretAuthTag: text("secret_auth_tag").notNull(),
    /** Masked display value, e.g. `whsec_…4f2a`. Safe to return. */
    secretHint: varchar("secret_hint", { length: 64 }),
    secretRotatedAt: timestamp("secret_rotated_at", { withTimezone: true }),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    lastDeliveryAt: timestamp("last_delivery_at", { withTimezone: true }),
    lastDeliveryStatus: varchar("last_delivery_status", { length: 32 }),
    disabledAt: timestamp("disabled_at", { withTimezone: true }),
    disabledReason: text("disabled_reason"),
  },
  (t) => [
    index("webhook_subscriptions_workspace_idx").on(t.workspaceId),
    index("webhook_subscriptions_active_idx").on(t.workspaceId, t.active),
    uniqueIndex("webhook_subscriptions_name_uidx")
      .on(t.workspaceId, t.name)
      .where(isNull(t.deletedAt)),
  ],
)

export type WebhookSubscriptionRow = typeof webhookSubscriptions.$inferSelect
export type NewWebhookSubscriptionRow = typeof webhookSubscriptions.$inferInsert

export const webhookDeliveries = pgTable(
  "webhook_deliveries",
  {
    ...baseColumns,
    ...workspaceColumn,
    subscriptionId: uuid("subscription_id")
      .notNull()
      .references(() => webhookSubscriptions.id, { onDelete: "cascade" }),
    eventId: varchar("event_id", { length: 128 }).notNull(),
    eventName: varchar("event_name", { length: 128 }).notNull(),
    status: varchar("status", { length: 32 }).notNull().default("pending"),
    /** Exact bytes to sign and POST — re-serialising would break the HMAC. */
    body: text("body").notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    maxAttempts: integer("max_attempts").notNull().default(6),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
    attempts: jsonb("attempts").$type<WebhookDeliveryAttemptRecord[]>().notNull().default([]),
    lastStatusCode: integer("last_status_code"),
    lastResponseSnippet: text("last_response_snippet"),
    lastDurationMs: integer("last_duration_ms"),
    lastError: text("last_error"),
    succeededAt: timestamp("succeeded_at", { withTimezone: true }),
    deadLetteredAt: timestamp("dead_lettered_at", { withTimezone: true }),
    deadLetterReason: text("dead_letter_reason"),
    replayOfId: uuid("replay_of_id"),
  },
  (t) => [
    index("webhook_deliveries_workspace_idx").on(t.workspaceId),
    index("webhook_deliveries_subscription_idx").on(t.subscriptionId, t.createdAt),
    index("webhook_deliveries_status_idx").on(t.workspaceId, t.status),
    // NOT filtered on deleted_at: a retried job must never double-deliver,
    // including against a row an operator soft-deleted.
    uniqueIndex("webhook_deliveries_idempotency_uidx").on(t.subscriptionId, t.eventId),
  ],
)

export type WebhookDeliveryRow = typeof webhookDeliveries.$inferSelect
export type NewWebhookDeliveryRow = typeof webhookDeliveries.$inferInsert

export const publicApiKeys = pgTable(
  "api_keys",
  {
    ...baseColumns,
    ...workspaceColumn,
    name: varchar("name", { length: 255 }).notNull(),
    /** SHA-256 hex of the raw key. The raw key is never persisted. */
    keyHash: varchar("key_hash", { length: 64 }).notNull(),
    keyPrefix: varchar("key_prefix", { length: 32 }).notNull(),
    lastFour: varchar("last_four", { length: 8 }).notNull(),
    role: varchar("role", { length: 32 }).notNull().default("viewer"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by"),
  },
  (t) => [
    index("api_keys_workspace_idx").on(t.workspaceId),
    // Global: a presented key is looked up by hash before any workspace is
    // known, so the uniqueness cannot be scoped to one.
    uniqueIndex("api_keys_hash_uidx").on(t.keyHash),
  ],
)

export type PublicApiKeyRow = typeof publicApiKeys.$inferSelect
export type NewPublicApiKeyRow = typeof publicApiKeys.$inferInsert
