import { sql } from "drizzle-orm"
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core"
import { baseColumns, workspaceColumn } from "./base"

/**
 * Conversation-intelligence tables (spec 37-ai-conversation-intelligence,
 * P0). Migration `0410_conversation_intelligence.sql`.
 *
 * Two tables:
 *
 *  - `conversationAnalyses` — one AI reading of one conversation: a
 *    summary, a sentiment signal, extracted action items or the key
 *    topics. Every row carries full attribution (provider, model, run id,
 *    tokens, latency) plus the cost-control facts (`sourceChars`,
 *    `analysedChars`, `truncated`).
 *  - `callTranscripts` — the text of a call or meeting. INGESTED, never
 *    produced here: this module does no audio processing.
 *
 * POLYMORPHIC SUBJECT, NO FOREIGN KEY
 * -----------------------------------
 * `subjectType` + `subjectId` name the conversation. Email threads,
 * WhatsApp conversations and calls belong to other modules, so `subjectId`
 * is a plain uuid with an index and no FK — the rule every cross-module
 * reference in this schema follows (`people.companyId`, `aiRuns.actorId`).
 * The domain service resolves a subject through the OWNING module's
 * service, which is what makes permission inheritance real.
 *
 * NO VISIBILITY COLUMN ON PURPOSE
 * -------------------------------
 * An analysis is readable exactly when its subject is, re-resolved on
 * every read. A copied `visibleTo` column would go stale the moment the
 * thread is reassigned.
 *
 * WHY TOKENS LIVE HERE AND NOT IN `ai_runs`
 * -----------------------------------------
 * `aiRuns.conversationId` is NOT NULL and references `aiConversations` —
 * an assistant chat thread, which an analysis does not have. So an
 * analysis keeps its own accounting and reuses the same column names, and
 * spec 38's usage rollups can UNION the two. `runId` is generated by this
 * module, appears on every audit row for the analysis, and references no
 * table.
 *
 * NEVER STORED HERE
 * -----------------
 * No prompt text, no transcript excerpt, no raw provider error body.
 * `output` is the model's structured answer only. `errorMessage` has had
 * every run of source text removed before it arrives.
 */

export const CONVERSATION_SUBJECT_TYPE_VALUES = [
  "email_thread",
  "whatsapp_conversation",
  "call",
] as const

export type ConversationSubjectTypeValue = (typeof CONVERSATION_SUBJECT_TYPE_VALUES)[number]

export function isConversationSubjectType(value: unknown): value is ConversationSubjectTypeValue {
  return (
    typeof value === "string" &&
    (CONVERSATION_SUBJECT_TYPE_VALUES as readonly string[]).includes(value)
  )
}

export const CONVERSATION_ANALYSIS_TYPE_VALUES = [
  "summary",
  "sentiment",
  "action_items",
  "key_topics",
] as const

export type ConversationAnalysisTypeValue = (typeof CONVERSATION_ANALYSIS_TYPE_VALUES)[number]

export function isConversationAnalysisType(value: unknown): value is ConversationAnalysisTypeValue {
  return (
    typeof value === "string" &&
    (CONVERSATION_ANALYSIS_TYPE_VALUES as readonly string[]).includes(value)
  )
}

export const CONVERSATION_ANALYSIS_STATUS_VALUES = ["queued", "succeeded", "failed"] as const

export type ConversationAnalysisStatusValue = (typeof CONVERSATION_ANALYSIS_STATUS_VALUES)[number]

export function isConversationAnalysisStatus(
  value: unknown,
): value is ConversationAnalysisStatusValue {
  return (
    typeof value === "string" &&
    (CONVERSATION_ANALYSIS_STATUS_VALUES as readonly string[]).includes(value)
  )
}

export const CALL_TRANSCRIPT_SOURCE_VALUES = ["provider", "manual"] as const

export type CallTranscriptSourceValue = (typeof CALL_TRANSCRIPT_SOURCE_VALUES)[number]

export function isCallTranscriptSource(value: unknown): value is CallTranscriptSourceValue {
  return (
    typeof value === "string" &&
    (CALL_TRANSCRIPT_SOURCE_VALUES as readonly string[]).includes(value)
  )
}

/** One AI reading of one conversation. */
export const conversationAnalyses = pgTable(
  "conversation_analyses",
  {
    ...baseColumns,
    ...workspaceColumn,
    /** Which kind of conversation. See the header. */
    subjectType: varchar("subject_type", { length: 32 }).notNull(),
    /** Email thread / WhatsApp conversation / call id. Plain uuid, no FK. */
    subjectId: uuid("subject_id").notNull(),
    analysisType: varchar("analysis_type", { length: 32 }).notNull(),
    status: varchar("status", { length: 16 }).notNull().default("queued"),
    /** Attribution (spec 37 §14). Null until the run completes. */
    providerId: varchar("provider_id", { length: 64 }),
    model: varchar("model", { length: 128 }),
    /** This module's own run id; carried by every audit row it writes. */
    runId: uuid("run_id"),
    /** The model's structured answer. Never the source conversation. */
    output: jsonb("output"),
    promptTokens: integer("prompt_tokens").notNull().default(0),
    completionTokens: integer("completion_tokens").notNull().default(0),
    totalTokens: integer("total_tokens").notNull().default(0),
    latencyMs: integer("latency_ms").notNull().default(0),
    /** Characters in the conversation before truncation. */
    sourceChars: integer("source_chars").notNull().default(0),
    /** Characters actually sent to the provider. */
    analysedChars: integer("analysed_chars").notNull().default(0),
    truncated: boolean("truncated").notNull().default(false),
    /** `users.id` of whoever asked. Plain uuid, no FK. */
    requestedBy: uuid("requested_by"),
    analysedAt: timestamp("analysed_at", { withTimezone: true }),
    errorCode: varchar("error_code", { length: 64 }),
    /** Redacted of all source text before it reaches this column. */
    errorMessage: varchar("error_message", { length: 500 }),
    correlationId: varchar("correlation_id", { length: 128 }),
  },
  (t) => [
    index("conversation_analyses_workspace_idx").on(t.workspaceId),
    // The detail query: every analysis of one conversation, newest first.
    index("conversation_analyses_subject_idx").on(
      t.workspaceId,
      t.subjectType,
      t.subjectId,
      t.createdAt,
    ),
    index("conversation_analyses_type_idx").on(t.workspaceId, t.analysisType, t.createdAt),
    index("conversation_analyses_status_idx").on(t.workspaceId, t.status, t.createdAt),
    index("conversation_analyses_run_idx").on(t.runId),
    check(
      "conversation_analyses_subject_type_chk",
      sql`${t.subjectType} IN ('email_thread', 'whatsapp_conversation', 'call')`,
    ),
    check(
      "conversation_analyses_type_chk",
      sql`${t.analysisType} IN ('summary', 'sentiment', 'action_items', 'key_topics')`,
    ),
    check(
      "conversation_analyses_status_chk",
      sql`${t.status} IN ('queued', 'succeeded', 'failed')`,
    ),
  ],
)

export type ConversationAnalysisRow = typeof conversationAnalyses.$inferSelect
export type NewConversationAnalysisRow = typeof conversationAnalyses.$inferInsert

/**
 * An ingested call/meeting transcript.
 *
 * THE SPEECH-TO-TEXT SEAM. Rows arrive either from a provider/notetaker
 * payload (`source = 'provider'`, `externalId` makes re-delivery
 * idempotent) or from a human paste (`source = 'manual'`). Wiring a real
 * STT provider means writing rows here through the same ingest path —
 * nothing downstream changes.
 */
export const callTranscripts = pgTable(
  "call_transcripts",
  {
    ...baseColumns,
    ...workspaceColumn,
    subjectType: varchar("subject_type", { length: 32 }).notNull().default("call"),
    /** Call / meeting id. Plain uuid, no FK. */
    subjectId: uuid("subject_id").notNull(),
    source: varchar("source", { length: 16 }).notNull(),
    /** Notetaker or STT provider. Null for a manual paste. */
    providerId: varchar("provider_id", { length: 64 }),
    /** Provider transcript id; unique per workspace (idempotent inbound). */
    externalId: varchar("external_id", { length: 255 }),
    language: varchar("language", { length: 16 }),
    text: text("text").notNull(),
    /** `[{ speaker, startMs, endMs, text }]`, as the provider reported it. */
    segments: jsonb("segments"),
    durationMs: integer("duration_ms"),
    speakerCount: integer("speaker_count").notNull().default(0),
    charCount: integer("char_count").notNull().default(0),
  },
  (t) => [
    index("call_transcripts_workspace_idx").on(t.workspaceId),
    index("call_transcripts_subject_idx").on(
      t.workspaceId,
      t.subjectType,
      t.subjectId,
      t.createdAt,
    ),
    uniqueIndex("call_transcripts_external_idx")
      .on(t.workspaceId, t.externalId)
      .where(sql`${t.externalId} IS NOT NULL AND ${t.deletedAt} IS NULL`),
    check(
      "call_transcripts_subject_type_chk",
      sql`${t.subjectType} IN ('email_thread', 'whatsapp_conversation', 'call')`,
    ),
    check("call_transcripts_source_chk", sql`${t.source} IN ('provider', 'manual')`),
  ],
)

export type CallTranscriptRow = typeof callTranscripts.$inferSelect
export type NewCallTranscriptRow = typeof callTranscripts.$inferInsert
