export {
  createAiGovernanceService,
  aiActionCorrelationId,
  AiActionAlreadyDecidedError,
  AiActionRequestNotFoundError,
  AiActionStateError,
  AiPolicyNotFoundError,
  AI_ACTION_CORRELATION_PREFIX,
  AI_GOVERNANCE_SERVICE_METHODS,
} from "./service"
export type { AiGovernanceService } from "./service"
export {
  assertAiActionAllowed,
  assertAiActorResolved,
  assertHumanApprover,
  assertNotSelfApproval,
  aiActionPermission,
  aiGovernancePermission,
  AiSelfApprovalError,
  AI_ACTION_OBJECT,
  AI_ACTION_PERMISSIONS,
  AI_POLICY_OBJECT,
} from "./access"
export type { AiActionTarget } from "./access"
export {
  aiPolicySpecificity,
  describeAiPolicyModes,
  resolveAiPolicy,
  AI_POLICY_DEFAULT_MODE,
} from "./policy"
export type { AiPolicyResolution, AiPolicyScope } from "./policy"
export {
  aiActionApprovalSchema,
  aiActionRequestQuerySchema,
  aiActionRequestSchema,
  aiActionRequestStatusSchema,
  aiActionTypeSchema,
  aiActorTypeSchema,
  aiPolicyModeSchema,
  aiPolicyQuerySchema,
  aiPolicySchema,
  approveAiActionSchema,
  createAiActionRequestSchema,
  createAiPolicySchema,
  rejectAiActionSchema,
  revertAiActionSchema,
  updateAiPolicySchema,
  AI_ACTION_DEFAULT_TTL_MINUTES,
  AI_ACTION_REQUEST_STATUSES,
  AI_ACTION_TYPES,
  AI_ACTOR_TYPES,
  AI_POLICY_MODES,
  AI_POLICY_WILDCARD,
} from "./schemas"
export type {
  AiActionApprovalDto,
  AiActionRequestDto,
  AiActionRequestQuery,
  AiActionRequestStatus,
  AiActionType,
  AiActorType,
  AiPolicyDto,
  AiPolicyMode,
  AiPolicyQuery,
  ApproveAiActionInput,
  CreateAiActionRequestInput,
  CreateAiPolicyInput,
  RejectAiActionInput,
  RevertAiActionInput,
  UpdateAiPolicyInput,
} from "./schemas"
export type {
  AiActionApplierPort,
  AiActionApplyOutcome,
  AiActionApplyResult,
  AiActionApprovalRecord,
  AiActionClaim,
  AiActionDecisionOutcome,
  AiActionMutation,
  AiActionProposalPort,
  AiActionRequestListQuery,
  AiActionRequestListResult,
  AiActionRequestOutcome,
  AiActionRequestRecord,
  AiActionRevertOutcome,
  AiActorRoleResolver,
  AiGovernanceAuditInput,
  AiGovernanceServiceContext,
  AiGovernanceServiceDeps,
  AiGovernanceStore,
  AiPolicyListQuery,
  AiPolicyListResult,
  AiPolicyRecord,
} from "./types"
// Shared across every CRM module — see ../ports.ts for why they live there.
export type { AuditWriter, EventEmitter } from "../ports"
