import { z } from "zod"
import { paginationQuerySchema } from "@yourcrm/validation"
import { isSubscribableEventName, SUBSCRIBABLE_EVENT_NAMES } from "./event-names"
import { checkWebhookUrl } from "./url-guard"
import { WEBHOOK_MAX_ATTEMPTS } from "./retry"

/**
 * Outbound-webhook and API-key zod schemas. Services validate inputs with
 * these; API routes reuse them at the HTTP boundary via
 * `@hono/zod-validator`.
 *
 * SECRETS: the signing secret and the raw API key appear in exactly TWO
 * response shapes in this file — `webhookSubscriptionCreatedSchema` and
 * `publicApiKeyCreatedSchema`, the once-only reveals. Every other response
 * schema here has no field a secret could occupy. That is the strongest
 * form of "secrets never leave": not a redaction step that can be
 * forgotten, but a shape with nowhere to put one.
 */

/* ------------------------------ requests ------------------------------ */

/**
 * A webhook target, checked against the SSRF policy at parse time.
 *
 * The guard also runs inside the service and again before every delivery
 * attempt. Having it here too means a bad URL is a 400 with a reason the
 * admin can act on, instead of a 500 from somewhere deeper.
 */
export const webhookTargetUrlSchema = z
  .string()
  .trim()
  .min(1)
  .max(2048)
  .superRefine((value, ctx) => {
    const result = checkWebhookUrl(value)
    if (!result.allowed) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: result.reason })
    }
  })

/** Event names must exist in `@yourcrm/events`; see event-names.ts. */
export const subscribedEventNameSchema = z
  .string()
  .trim()
  .refine(isSubscribableEventName, (value) => ({
    message: `"${value}" is not a known domain event`,
  }))

export const subscribedEventNamesSchema = z
  .array(subscribedEventNameSchema)
  .min(1, "subscribe to at least one event")
  .max(SUBSCRIBABLE_EVENT_NAMES.length)
  .transform((names) => [...new Set(names)].sort())

export const createWebhookSubscriptionSchema = z.object({
  name: z.string().trim().min(1).max(255),
  description: z.string().trim().max(2000).nullish(),
  targetUrl: webhookTargetUrlSchema,
  eventNames: subscribedEventNamesSchema,
  active: z.boolean().default(true),
})

export type CreateWebhookSubscriptionInput = z.infer<typeof createWebhookSubscriptionSchema>

/**
 * No `secret` field, deliberately. The signing secret is generated by the
 * server on create and on rotate, and shown once. A caller-supplied secret
 * would arrive through logs, browser history and CI variables before it
 * ever reached the cipher.
 */
export const updateWebhookSubscriptionSchema = z
  .object({
    name: z.string().trim().min(1).max(255),
    description: z.string().trim().max(2000).nullable(),
    targetUrl: webhookTargetUrlSchema,
    eventNames: subscribedEventNamesSchema,
    active: z.boolean(),
  })
  .partial()
  .refine((value) => Object.keys(value).length > 0, { message: "patch must not be empty" })

export type UpdateWebhookSubscriptionInput = z.infer<typeof updateWebhookSubscriptionSchema>

export const webhookSubscriptionQuerySchema = paginationQuerySchema.extend({
  active: z
    .union([z.boolean(), z.enum(["true", "false"])])
    .transform((value) => value === true || value === "true")
    .optional(),
  event: subscribedEventNameSchema.optional(),
})

export type WebhookSubscriptionQuery = z.infer<typeof webhookSubscriptionQuerySchema>

export const webhookDeliveryStatusSchema = z.enum([
  "pending",
  "delivering",
  "succeeded",
  "failed",
  "dead_lettered",
])

export const webhookDeliveryQuerySchema = paginationQuerySchema.extend({
  subscriptionId: z.string().min(1).max(128).optional(),
  status: webhookDeliveryStatusSchema.optional(),
  event: subscribedEventNameSchema.optional(),
})

export type WebhookDeliveryQuery = z.infer<typeof webhookDeliveryQuerySchema>

export const publicApiKeyRoleSchema = z.enum(["owner", "admin", "member", "viewer"])

export type PublicApiKeyRole = z.infer<typeof publicApiKeyRoleSchema>

export const createPublicApiKeySchema = z.object({
  name: z.string().trim().min(1).max(255),
  /** Clamped against the creator's own role by the service (spec 32 §8). */
  role: publicApiKeyRoleSchema.default("viewer"),
  expiresAt: z.coerce.date().nullish(),
})

export type CreatePublicApiKeyInput = z.infer<typeof createPublicApiKeySchema>

export const publicApiKeyQuerySchema = paginationQuerySchema.extend({
  includeRevoked: z
    .union([z.boolean(), z.enum(["true", "false"])])
    .transform((value) => value === true || value === "true")
    .optional(),
})

export type PublicApiKeyQuery = z.infer<typeof publicApiKeyQuerySchema>

/* ------------------------------ responses ----------------------------- */

export const webhookSubscriptionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  targetUrl: z.string(),
  eventNames: z.array(z.string()),
  active: z.boolean(),
  /** Masked, e.g. `whsec_…4f2a`. The only secret-derived value returned. */
  secretHint: z.string().nullable().optional(),
  secretRotatedAt: z.unknown(),
  consecutiveFailures: z.number().int().nonnegative().optional(),
  lastDeliveryAt: z.unknown(),
  lastDeliveryStatus: z.string().nullable().optional(),
  disabledAt: z.unknown(),
  disabledReason: z.string().nullable().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
})

export type WebhookSubscriptionDto = z.infer<typeof webhookSubscriptionSchema>

/**
 * ONE of the two shapes in this module that carries a secret, returned
 * only by `POST /subscriptions` and `POST /subscriptions/:id/secret`.
 */
export const webhookSubscriptionCreatedSchema = z.object({
  subscription: webhookSubscriptionSchema,
  /** Shown exactly once. Not stored in plaintext and not recoverable. */
  signingSecret: z.string(),
})

export type WebhookSubscriptionCreatedDto = z.infer<typeof webhookSubscriptionCreatedSchema>

export const webhookDeliveryAttemptSchema = z.object({
  attempt: z.number().int().positive(),
  at: z.string(),
  outcome: z.enum(["succeeded", "transient", "permanent"]),
  statusCode: z.number().int().nullable(),
  durationMs: z.number().int().nonnegative(),
  responseSnippet: z.string().nullable(),
  error: z.string().nullable(),
})

export const webhookDeliverySchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  subscriptionId: z.string(),
  eventId: z.string(),
  eventName: z.string(),
  status: z.string(),
  attemptCount: z.number().int().nonnegative(),
  maxAttempts: z.number().int().positive().max(WEBHOOK_MAX_ATTEMPTS),
  nextAttemptAt: z.unknown(),
  attempts: z.array(webhookDeliveryAttemptSchema).default([]),
  lastStatusCode: z.number().int().nullable().optional(),
  lastResponseSnippet: z.string().nullable().optional(),
  lastDurationMs: z.number().int().nullable().optional(),
  lastError: z.string().nullable().optional(),
  succeededAt: z.unknown(),
  deadLetteredAt: z.unknown(),
  deadLetterReason: z.string().nullable().optional(),
  replayOfId: z.string().nullable().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
})

export type WebhookDeliveryDto = z.infer<typeof webhookDeliverySchema>

export const publicApiKeySchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string(),
  role: z.string(),
  keyPrefix: z.string(),
  lastFour: z.string(),
  expiresAt: z.unknown(),
  lastUsedAt: z.unknown(),
  revokedAt: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
})

export type PublicApiKeyDto = z.infer<typeof publicApiKeySchema>

/** The other once-only reveal. Returned by `POST /keys` and nothing else. */
export const publicApiKeyCreatedSchema = z.object({
  apiKey: publicApiKeySchema,
  /** Shown exactly once. Only its SHA-256 hash is persisted. */
  key: z.string(),
})

export type PublicApiKeyCreatedDto = z.infer<typeof publicApiKeyCreatedSchema>

export const subscribableEventSchema = z.object({
  name: z.string(),
  domain: z.string(),
})

export type SubscribableEventDto = z.infer<typeof subscribableEventSchema>
