/**
 * `@yourcrm/integrations` — the provider contract.
 *
 * WHAT THIS IS
 * ------------
 * The single typed description of "a third-party system YourCRM can connect
 * to". Email, WhatsApp and calling adapters all implement THIS shape; the
 * framework (connection records, credential storage, health checks, webhook
 * ingestion) is written once against it and knows nothing about any vendor.
 *
 * Nothing in this package hardcodes a vendor list. Providers are registered
 * into a registry (see `./registry.ts`); the catalogue an API response shows
 * is whatever is registered at runtime.
 *
 * MIRRORED CONTRACT (read this before you change a type here)
 * -----------------------------------------------------------
 * `packages/crm/src/integrations/types.ts` declares `IntegrationProviderPort`
 * and friends as a *structural mirror* of the types below. That mirror exists
 * because `@yourcrm/crm` does not declare `@yourcrm/integrations` as a
 * dependency yet (bun workspaces symlink only declared deps, so the import
 * would not resolve — reported as a blocker to the integrator). The mirror is
 * the same pattern `packages/crm/src/ports.ts` already uses for
 * `WriteAuditInput`. Keep the two files in sync until the dependency is wired,
 * at which point the mirror collapses into a re-export.
 */

/**
 * Minimal structural shape of a config validator. Every zod schema satisfies
 * it (`z.object({...})`), and typing it structurally keeps the contract
 * mirrorable into `@yourcrm/crm` without a zod version coupling.
 */
export type IntegrationConfigSchema = {
  parse(value: unknown): unknown
}

/** Lifecycle state of one installed connection. Persisted verbatim. */
export const INTEGRATION_CONNECTION_STATUSES = ["connected", "disconnected", "error"] as const

export type IntegrationConnectionStatus = (typeof INTEGRATION_CONNECTION_STATUSES)[number]

export function isIntegrationConnectionStatus(
  value: unknown,
): value is IntegrationConnectionStatus {
  return (
    typeof value === "string" &&
    (INTEGRATION_CONNECTION_STATUSES as readonly string[]).includes(value)
  )
}

/**
 * What a provider can do. The framework never branches on a provider id —
 * downstream modules select providers by capability
 * (`registry.list().filter((p) => p.capabilities.includes("email.send"))`).
 */
export const INTEGRATION_CAPABILITIES = [
  "email.send",
  "email.receive",
  "messaging.send",
  "messaging.receive",
  "calling.place",
  "calling.receive",
  "calling.recording",
  "calendar.sync",
  "contacts.sync",
  "payments",
  "accounting",
  "chat.notify",
  "automation.webhook",
  "analytics",
] as const

export type IntegrationCapability = (typeof INTEGRATION_CAPABILITIES)[number]

export function isIntegrationCapability(value: unknown): value is IntegrationCapability {
  return (
    typeof value === "string" && (INTEGRATION_CAPABILITIES as readonly string[]).includes(value)
  )
}

/** Catalogue grouping for the integrations page (spec 31 §3). */
export const INTEGRATION_CATEGORIES = [
  "email",
  "calendar",
  "messaging",
  "calling",
  "payments",
  "accounting",
  "chat",
  "automation",
  "analytics",
  "lead-source",
  "other",
] as const

export type IntegrationCategory = (typeof INTEGRATION_CATEGORIES)[number]

/**
 * How a connection authenticates.
 *
 * P0 ships `api_key` only. `oauth2` is declared so the contract, the storage
 * columns and the UI copy are already shaped for it — see the OAuth extension
 * point note at the bottom of this file. The domain service rejects `oauth2`
 * connect attempts today with a clear error instead of half-implementing a
 * redirect flow.
 */
export const INTEGRATION_AUTH_KINDS = ["api_key", "oauth2"] as const

export type IntegrationAuthKind = (typeof INTEGRATION_AUTH_KINDS)[number]

/**
 * Credential slots on a connection. One row per (connection, kind).
 *
 * - `api_key`    — the provider secret the workspace pasted in.
 * - `webhook_secret` — the HMAC shared secret inbound deliveries are signed
 *   with. Generated by the framework at connect time when the provider
 *   declares a webhook spec.
 * - `oauth_tokens` — reserved for the OAuth extension point (unused in P0).
 */
export const INTEGRATION_CREDENTIAL_KINDS = ["api_key", "webhook_secret", "oauth_tokens"] as const

export type IntegrationCredentialKind = (typeof INTEGRATION_CREDENTIAL_KINDS)[number]

export function isIntegrationCredentialKind(value: unknown): value is IntegrationCredentialKind {
  return (
    typeof value === "string" && (INTEGRATION_CREDENTIAL_KINDS as readonly string[]).includes(value)
  )
}

/**
 * Runtime handle handed to every lifecycle hook.
 *
 * `secret` is the DECRYPTED provider credential, in memory, for the duration
 * of the call only. Providers must never persist, log or echo it.
 */
export type IntegrationProviderContext = {
  workspaceId: string
  connectionId: string
  /** Non-secret settings, already validated by `configSchema`. */
  config: Record<string, unknown>
  /** Decrypted API key, or null when the connection has no secret yet. */
  secret: string | null
}

/** Input to `connect()`: the workspace's first handshake with the provider. */
export type IntegrationConnectInput = IntegrationProviderContext & {
  displayName: string
}

/**
 * Result of `connect()`. Everything is optional: a provider that only needs
 * to verify the key returns `{}`.
 */
export type IntegrationConnectResult = {
  /** Provider-side account/tenant id (mailbox, WABA id, phone number, …). */
  externalAccountId?: string | null
  /** Overrides the user-supplied display name (e.g. the real mailbox name). */
  displayName?: string | null
  /** Granted scopes, stored as credential metadata (never the secret). */
  scopes?: readonly string[]
  /** Config to persist back (normalised endpoints, discovered ids, …). */
  config?: Record<string, unknown>
}

/** Result of `healthCheck()`. `error` is surfaced on the connection record. */
export type IntegrationHealthResult = {
  status: IntegrationConnectionStatus
  /** Short human-readable reason. Never include the credential. */
  message?: string | null
}

/** One verified inbound delivery, after signature + idempotency checks. */
export type IntegrationWebhookDelivery = {
  workspaceId: string
  connectionId: string
  providerId: string
  /** The connection's non-secret config — handlers need it for routing. */
  config: Record<string, unknown>
  /** Provider-side event id — the idempotency key. */
  providerEventId: string
  eventType: string | null
  /** Lower-cased request headers. */
  headers: Readonly<Record<string, string>>
  /** Exact bytes the signature was computed over. */
  rawBody: string
  /** `JSON.parse(rawBody)`, or the raw string when the body is not JSON. */
  payload: unknown
}

/** What the provider did with a delivery. Recorded on the webhook event row. */
export type IntegrationWebhookOutcome = {
  status: "processed" | "ignored"
  /** Normalised event type, when the provider can classify it. */
  eventType?: string | null
  /** Short note for the error queue / audit trail. Never include payload PII. */
  detail?: string | null
}

/**
 * How inbound webhooks for this provider are authenticated and identified.
 *
 * The framework — not the provider — verifies the signature, in constant
 * time, against the connection's stored `webhook_secret`. The provider only
 * declares WHERE the signature is and HOW it is encoded, then handles the
 * verified payload.
 */
export type IntegrationWebhookSpec = {
  /** Header carrying the HMAC, e.g. `x-hub-signature-256`. Case-insensitive. */
  signatureHeader: string
  /** HMAC digest algorithm. */
  algorithm: "sha1" | "sha256" | "sha512"
  /** Digest encoding in the header. Defaults to `hex`. */
  encoding?: "hex" | "base64"
  /** Literal prefix to strip before comparing, e.g. `sha256=`. */
  signaturePrefix?: string
  /** Header carrying the provider event id, when the id is not in the body. */
  eventIdHeader?: string
  /** Pull the idempotency key out of the payload. Return null to fall back. */
  extractEventId?: (payload: unknown, headers: Readonly<Record<string, string>>) => string | null
  /** Classify the delivery (`message.received`, `call.completed`, …). */
  extractEventType?: (payload: unknown, headers: Readonly<Record<string, string>>) => string | null
  /** Called once per unique `providerEventId`. Must be idempotent anyway. */
  handle: (delivery: IntegrationWebhookDelivery) => Promise<IntegrationWebhookOutcome>
}

/**
 * The provider contract. Implement this (via {@link defineIntegrationProvider})
 * and register it; the framework does the rest.
 *
 * Hooks must be side-effect free at module scope: no network or database work
 * until a hook is actually called.
 */
export type IntegrationProvider = {
  /** Stable machine id, `^[a-z0-9][a-z0-9_-]{1,62}$`. Persisted on rows. */
  readonly id: string
  readonly displayName: string
  readonly description?: string
  readonly category: IntegrationCategory
  readonly capabilities: readonly IntegrationCapability[]
  /** P0 providers use `api_key`. */
  readonly authKind: IntegrationAuthKind
  /** Validates the non-secret settings supplied at connect time. */
  readonly configSchema: IntegrationConfigSchema
  /** Label for the secret input, e.g. "API key", "Auth token". */
  readonly secretLabel?: string
  /** Link shown next to the provider in the catalogue. */
  readonly docsUrl?: string
  /** Declared when the provider receives inbound webhooks. */
  readonly webhook?: IntegrationWebhookSpec

  /** Verify the credential and discover account metadata. Throw to fail. */
  connect(input: IntegrationConnectInput): Promise<IntegrationConnectResult>
  /** Best-effort revocation on the provider side. Must not throw on 404. */
  disconnect(ctx: IntegrationProviderContext): Promise<void>
  /** Cheap liveness probe. Returns a status instead of throwing. */
  healthCheck(ctx: IntegrationProviderContext): Promise<IntegrationHealthResult>
}

const PROVIDER_ID_RE = /^[a-z0-9][a-z0-9_-]{1,62}$/

export class InvalidIntegrationProviderError extends Error {
  readonly code = "INVALID_PROVIDER"
  constructor(message: string) {
    super(message)
    this.name = "InvalidIntegrationProviderError"
  }
}

/**
 * Identity helper with validation: authoring a provider through this catches
 * a malformed id or an unknown capability at import time rather than on the
 * first connect attempt.
 *
 * ```ts
 * export const resendProvider = defineIntegrationProvider({
 *   id: "resend",
 *   displayName: "Resend",
 *   category: "email",
 *   capabilities: ["email.send"],
 *   authKind: "api_key",
 *   configSchema: z.object({ fromAddress: z.string().email() }),
 *   connect: async ({ secret }) => ({ externalAccountId: await whoami(secret) }),
 *   disconnect: async () => undefined,
 *   healthCheck: async ({ secret }) => ({ status: (await ping(secret)) ? "connected" : "error" }),
 * })
 * ```
 */
export function defineIntegrationProvider(provider: IntegrationProvider): IntegrationProvider {
  if (!PROVIDER_ID_RE.test(provider.id)) {
    throw new InvalidIntegrationProviderError(
      `provider id "${provider.id}" must match ${String(PROVIDER_ID_RE)}`,
    )
  }
  if (provider.displayName.trim().length === 0) {
    throw new InvalidIntegrationProviderError(`provider "${provider.id}" needs a displayName`)
  }
  if (provider.capabilities.length === 0) {
    throw new InvalidIntegrationProviderError(
      `provider "${provider.id}" must declare at least one capability`,
    )
  }
  for (const capability of provider.capabilities) {
    if (!isIntegrationCapability(capability)) {
      throw new InvalidIntegrationProviderError(
        `provider "${provider.id}" declares unknown capability "${String(capability)}"`,
      )
    }
  }
  return provider
}

/**
 * OAUTH EXTENSION POINT (deliberately NOT implemented in P0)
 * ----------------------------------------------------------
 * OAuth needs callback routing and a publicly reachable URL that this
 * deployment does not have yet, so P0 is API-key only. Everything needed to
 * add it later is already shaped:
 *
 * 1. `authKind: "oauth2"` exists on this contract; the domain service rejects
 *    it today in `connectIntegration()` with `OAUTH_NOT_SUPPORTED`.
 * 2. `INTEGRATION_CREDENTIAL_KINDS` includes `oauth_tokens`, and
 *    `integration_credentials` already has `scopes` + `expires_at` columns and
 *    a `key_version` column for rotation. No migration is needed to store a
 *    refresh token — it is just another sealed secret.
 * 3. Adding it means: (a) an optional `oauth?: { authorizeUrl(state), exchange(code),
 *    refresh(refreshToken) }` member on this type; (b) two routes —
 *    `GET /integrations/:providerId/oauth/start` and
 *    `GET /integrations/oauth/callback` — with CSRF state persisted per
 *    workspace; (c) a refresh-ahead job in `apps/worker` keyed on `expires_at`.
 * 4. Do NOT bolt a redirect flow onto `POST /integrations` — connect() stays
 *    the credential-verification hook for both auth kinds.
 */
