/**
 * Route-manifest generator for the API module registry.
 *
 * Scans `apps/api/src/routes/modules/` for `<slug>.ts` files and regenerates
 * `apps/api/src/routes/modules/index.ts` (the `moduleRoutes` list mounted by
 * `routes/v1.ts`).
 *
 * Module-file contract: each `<slug>.ts` must export `basePath` (string) and
 * `createRoutes()` (factory returning a `Hono<AppEnv>` sub-app), and may
 * export `openApiPaths` (record of full `/api/v1/...` path entries).
 *
 * Explicit generated manifest beats runtime filesystem globbing: Bun does
 * not support reliable globbing inside a built bundle, and a checked-in file
 * is debuggable in review.
 *
 * Usage:
 *   bun run scripts/gen-routes.ts          # regenerate
 *   bun run scripts/gen-routes.ts --check  # CI: fail on drift
 *   (wired as `bun run gen:routes` once the root package.json adds it —
 *   see scripts/README.md; editing package.json is outside this agent's scope)
 */
import { readdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

const ROOT = join(import.meta.dir, "..")
const MODULES_DIR = join(ROOT, "apps", "api", "src", "routes", "modules")
const MANIFEST = join(MODULES_DIR, "index.ts")

const HEADER = `// Code generated by scripts/gen-routes.ts. Do not edit by hand.
// Regenerate with: bun run scripts/gen-routes.ts (wired as \`bun run gen:routes\`).
`

function toIdentifier(slug: string): string {
  const camel = slug
    .split("-")
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("")
    .replace(/[^a-zA-Z0-9_]/g, "")
  const safe = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(camel) ? camel : `m${camel}`
  return safe.charAt(0).toLowerCase() + safe.slice(1)
}

type ModuleEntry = { slug: string; alias: string; hasOpenApi: boolean }

async function discover(): Promise<ModuleEntry[]> {
  const files = (await readdir(MODULES_DIR))
    .filter((f) => f.endsWith(".ts"))
    .filter((f) => f !== "index.ts" && f !== "types.ts" && !f.endsWith(".test.ts"))
    .sort()
  const entries: ModuleEntry[] = []
  for (const file of files) {
    const slug = file.slice(0, -".ts".length)
    const content = await readFile(join(MODULES_DIR, file), "utf8")
    const hasBasePath = /export\s+(const|let)\s+basePath\b/.test(content)
    const hasFactory = /export\s+function\s+createRoutes\b/.test(content)
    if (!hasBasePath || !hasFactory) {
      console.warn(`gen-routes: skipping ${file} (needs exports: basePath, createRoutes)`)
      continue
    }
    entries.push({
      slug,
      alias: toIdentifier(slug),
      hasOpenApi: /export\s+const\s+openApiPaths\b/.test(content),
    })
  }
  return entries
}

function render(entries: ModuleEntry[]): string {
  const lines: string[] = [HEADER, `import type { ModuleDefinition } from "./types"`]
  for (const e of entries) {
    const names = [
      `basePath as ${e.alias}BasePath`,
      `createRoutes as create${cap(e.alias)}Routes`,
      ...(e.hasOpenApi ? [`openApiPaths as ${e.alias}OpenApiPaths`] : []),
    ]
    if (names.length <= 2) {
      lines.push(`import { ${names.join(", ")} } from "./${e.slug}"`)
    } else {
      lines.push(`import {`)
      for (const n of names) lines.push(`  ${n},`)
      lines.push(`} from "./${e.slug}"`)
    }
  }
  lines.push(
    ``,
    `/**`,
    ` * Module registry — the single list \`routes/v1.ts\` mounts. Module agents`,
    ` * add \`routes/modules/<slug>.ts\` files exporting \`basePath\`,`,
    ` * \`createRoutes()\` and optionally \`openApiPaths\`, then run the generator`,
    ` * instead of editing this file or \`v1.ts\` by hand.`,
    ` */`,
    `export const moduleRoutes: ModuleDefinition[] = [`,
  )
  for (const e of entries) {
    const parts = [
      `path: ${e.alias}BasePath`,
      `createRoutes: create${cap(e.alias)}Routes`,
      ...(e.hasOpenApi ? [`openApiPaths: ${e.alias}OpenApiPaths`] : []),
    ]
    lines.push(`  { ${parts.join(", ")} },`)
  }
  lines.push(`]`, ``)
  return lines.join("\n")
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check")
  const entries = await discover()
  const next = render(entries)
  if (check) {
    const current = await readFile(MANIFEST, "utf8")
    if (current !== next) {
      console.error("gen-routes: manifest is stale — run `bun run scripts/gen-routes.ts`")
      process.exit(1)
    }
    console.log(`gen-routes: manifest up to date (${entries.length} module(s)).`)
    return
  }
  await writeFile(MANIFEST, next)
  console.log(
    `gen-routes: wrote ${entries.length} module(s) to apps/api/src/routes/modules/index.ts`,
  )
}

await main()
