import { zValidator } from "@hono/zod-validator"
import { roleInWorkspace, type Session } from "@yourcrm/auth"
import {
  applyCsPlaybookSchema,
  createCsAccountSchema,
  createCsRenewalSchema,
  createCustomerSuccessService,
  csAccountQuerySchema,
  csAccountSchema,
  csHealthScoreSchema,
  csPlaybookCatalogEntrySchema,
  csPlaybookTaskSchema,
  csRenewalQuerySchema,
  csRenewalSchema,
  updateCsAccountSchema,
  updateCsRenewalSchema,
  type CustomerSuccessService,
  type PlaybookTaskInput,
  type PlaybookTaskRecord,
  type TasksPort,
} from "@yourcrm/crm/src/customer-success"
import { createTasksService } from "@yourcrm/crm/src/tasks"
import { getDb, writeAudit } from "@yourcrm/database"
import {
  createCustomerSuccessRepository,
  describeCsPlaybooks,
  findCsPlaybook,
  type CreateCsAccountInput,
  type CreateCsRenewalInput,
  type CsAccountRowScope,
  type UpdateCsAccountInput,
  type UpdateCsRenewalInput,
} from "@yourcrm/database/src/repositories/customer-success-repository"
import { createTasksRepository } from "@yourcrm/database/src/repositories/tasks-repository"
import type {
  CreateTaskInput,
  UpdateTaskInput,
} from "@yourcrm/database/src/repositories/tasks-repository"
import { getEventBus } from "@yourcrm/events"
import { PermissionDeniedError } from "@yourcrm/permissions"
import { errorEnvelope, paginatedEnvelopeSchema } from "@yourcrm/validation"
import { Hono } from "hono"
import type { Context } from "hono"
import { z } from "zod"
import type { AppEnv } from "../../hono-env"
import { requireSession } from "../../middleware/auth"
import { zodToJsonSchema } from "../../openapi/zod-to-json-schema"

/**
 * Customer Success module (spec 46-customer-success, P0).
 *
 * Thin HTTP layer only: zod validation at the boundary, session from the
 * auth middleware, then straight into the domain service
 * (`@yourcrm/crm/src/customer-success`); `people.ts` is the golden
 * reference for the shape, `reports.ts` for the permission-filtered
 * aggregation shape.
 *
 * PLAYBOOK TASKS REUSE THE TASKS MODULE. `defaultService` below wires a
 * `TasksPort` onto the REAL tasks domain service (`createTasksService`,
 * same construction as `tasks.ts`'s own route file), so a playbook-created
 * task runs through normal task validation, audit and
 * `CrmEvents.TaskCreated` — this module never writes to the `tasks` table
 * directly and never re-implements a task engine.
 *
 * REGISTRY. `routes/modules/index.ts` is generated by `bun run gen:routes`;
 * this agent must not edit or regenerate it (same rule the unified-inbox
 * module documents), so the integrator's generator run is what mounts
 * `/api/v1/customer-success`. The exports below (`basePath`,
 * `createRoutes`, `openApiPaths`) are the contract that generator reads.
 */

export const basePath = "/customer-success"

const csAccountEnvelope = z.object({ data: csAccountSchema.passthrough() })
const csAccountListEnvelope = paginatedEnvelopeSchema(csAccountSchema.passthrough())
const csHealthScoreEnvelope = z.object({ data: csHealthScoreSchema.passthrough() })
const csHealthScoreListEnvelope = z.object({ data: z.array(csHealthScoreSchema.passthrough()) })
const csRenewalEnvelope = z.object({ data: csRenewalSchema.passthrough() })
const csRenewalListEnvelope = paginatedEnvelopeSchema(csRenewalSchema.passthrough())
const csPlaybookListEnvelope = z.object({ data: z.array(csPlaybookCatalogEntrySchema) })
const csPlaybookApplyEnvelope = z.object({ data: z.array(csPlaybookTaskSchema.passthrough()) })
const csPlaybookTaskListEnvelope = z.object({
  data: z.object({
    links: z.array(csPlaybookTaskSchema.passthrough()),
    tasks: z.array(z.record(z.string(), z.unknown())),
  }),
})

export type CustomerSuccessRouteDeps = {
  service?: CustomerSuccessService
}

function defaultService(): CustomerSuccessService {
  const db = getDb()
  const repository = createCustomerSuccessRepository()

  // Narrow port onto the tasks module's own domain service — see module
  // header. Constructed exactly like tasks.ts wires createTasksService.
  const tasksRepository = createTasksRepository()
  const tasksService = createTasksService({
    store: {
      list: (workspaceId, query) => tasksRepository.search(db, { workspaceId, ...query }),
      findById: (workspaceId, id) => tasksRepository.findById(db, workspaceId, id),
      create: (workspaceId, input, actorId) =>
        tasksRepository.create(db, workspaceId, input as unknown as CreateTaskInput, actorId),
      update: (workspaceId, id, input, actorId) =>
        tasksRepository.update(db, workspaceId, id, input as unknown as UpdateTaskInput, actorId),
      softDelete: async (workspaceId, id, actorId) => {
        await tasksRepository.softDelete(db, workspaceId, id, actorId)
      },
      restore: async (workspaceId, id) => {
        await tasksRepository.restore(db, workspaceId, id)
      },
    },
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "user" })
    },
    events: getEventBus(),
  })

  const tasksPort: TasksPort = {
    createTask: (ctx, input: PlaybookTaskInput) => tasksService.create(ctx, input),
    getTasks: async (ctx, ids) => {
      const found = await Promise.all(
        ids.map((id) =>
          tasksService
            .get(ctx, id)
            .then((task) => task as PlaybookTaskRecord)
            .catch(() => null),
        ),
      )
      return found.filter((task): task is PlaybookTaskRecord => task !== null)
    },
  }

  return createCustomerSuccessService({
    store: {
      listAccounts: (workspaceId, query, scope) =>
        repository.accounts.search(db, {
          workspaceId,
          scope: scope as CsAccountRowScope,
          ...query,
        }),
      findAccountById: (workspaceId, id, scope) =>
        repository.accounts.findById(db, workspaceId, id, scope as CsAccountRowScope),
      createAccount: (workspaceId, input, actorId) =>
        repository.accounts.create(
          db,
          workspaceId,
          input as unknown as CreateCsAccountInput,
          actorId,
        ),
      updateAccount: (workspaceId, id, input, actorId) =>
        repository.accounts.update(
          db,
          workspaceId,
          id,
          input as unknown as UpdateCsAccountInput,
          actorId,
        ),
      softDeleteAccount: async (workspaceId, id, actorId) => {
        await repository.accounts.softDelete(db, workspaceId, id, actorId)
      },
      restoreAccount: async (workspaceId, id) => {
        await repository.accounts.restore(db, workspaceId, id)
      },
      computeHealthFactors: (workspaceId, companyId) =>
        repository.healthScores.computeFactors(db, workspaceId, companyId),
      recordHealthScore: (workspaceId, accountId, computation, actorId) =>
        repository.healthScores.record(db, workspaceId, accountId, computation, actorId),
      listHealthScores: (workspaceId, accountId, limit) =>
        repository.healthScores.listForAccount(db, workspaceId, accountId, limit),
      listRenewals: (workspaceId, query, scope) =>
        repository.renewals.search(db, {
          workspaceId,
          scope: scope as CsAccountRowScope,
          ...query,
        }),
      findRenewalById: (workspaceId, id) => repository.renewals.findById(db, workspaceId, id),
      createRenewal: (workspaceId, input, actorId) =>
        repository.renewals.create(
          db,
          workspaceId,
          input as unknown as CreateCsRenewalInput,
          actorId,
        ),
      updateRenewal: (workspaceId, id, input, actorId) =>
        repository.renewals.update(
          db,
          workspaceId,
          id,
          input as unknown as UpdateCsRenewalInput,
          actorId,
        ),
      describePlaybooks: () => describeCsPlaybooks(),
      getPlaybook: (key) => findCsPlaybook(key),
      recordPlaybookApplication: (workspaceId, accountId, playbookKey, taskId, actorId) =>
        repository.playbookTasks.recordApplication(
          db,
          workspaceId,
          accountId,
          playbookKey,
          taskId,
          actorId,
        ),
      listPlaybookTasks: (workspaceId, accountId) =>
        repository.playbookTasks.listForAccount(db, workspaceId, accountId),
    },
    tasks: tasksPort,
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "user" })
    },
  })
}

function serviceContextOf(c: Context<AppEnv>) {
  const session = c.get("session") as Session | null
  return {
    workspaceId: session?.workspaceId ?? "",
    actorId: session?.user.id ?? "",
    role: session ? roleInWorkspace(session) : "viewer",
    correlationId: c.get("requestId") as string | undefined,
  }
}

function mapError(c: Context<AppEnv>, err: unknown) {
  const requestId = c.get("requestId") as string | undefined
  if (err instanceof PermissionDeniedError) {
    return c.json(errorEnvelope("FORBIDDEN", err.message, requestId), 403)
  }
  if (err instanceof Error && (err as { code?: string }).code === "NOT_FOUND") {
    return c.json(errorEnvelope("NOT_FOUND", err.message, requestId), 404)
  }
  if (err instanceof Error && (err as { code?: string }).code === "INVALID_PLAYBOOK") {
    return c.json(errorEnvelope("VALIDATION_ERROR", err.message, requestId), 400)
  }
  throw err
}

function invalidBody(c: Context, message: string, details: unknown) {
  return c.json(
    errorEnvelope("VALIDATION_ERROR", message, c.req.header("x-request-id") ?? undefined, details),
    400,
  )
}

export function createRoutes(deps: CustomerSuccessRouteDeps = {}) {
  const app = new Hono<AppEnv>()
  // Lazy default wiring: route construction must never touch the database —
  // registry and full-app tests mount every module without a live Postgres.
  let cached: CustomerSuccessService | null = deps.service ?? null
  const service = () => (cached ??= defaultService())

  /* --------------------------------- accounts --------------------------------- */

  app.get(
    "/accounts",
    requireSession(),
    zValidator("query", csAccountQuerySchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid query parameters", result.error.flatten())
    }),
    async (c) => {
      try {
        const result = await service().listAccounts(serviceContextOf(c), c.req.valid("query"))
        return c.json(result)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.post(
    "/accounts",
    requireSession(),
    zValidator("json", createCsAccountSchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid request body", result.error.flatten())
    }),
    async (c) => {
      try {
        const account = await service().createAccount(serviceContextOf(c), c.req.valid("json"))
        return c.json({ data: account }, 201)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/accounts/:id", requireSession(), async (c) => {
    try {
      const account = await service().getAccount(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: account })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.patch(
    "/accounts/:id",
    requireSession(),
    zValidator("json", updateCsAccountSchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid request body", result.error.flatten())
    }),
    async (c) => {
      try {
        const account = await service().updateAccount(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        return c.json({ data: account })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.delete("/accounts/:id", requireSession(), async (c) => {
    try {
      await service().deleteAccount(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: { deleted: true } })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.post("/accounts/:id/restore", requireSession(), async (c) => {
    try {
      const account = await service().restoreAccount(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: account })
    } catch (err) {
      return mapError(c, err)
    }
  })

  /* ------------------------------- health scores ------------------------------- */

  app.post("/accounts/:id/health-scores", requireSession(), async (c) => {
    try {
      const score = await service().recomputeHealthScore(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: score }, 201)
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.get("/accounts/:id/health-scores", requireSession(), async (c) => {
    try {
      const scores = await service().listHealthScores(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: scores })
    } catch (err) {
      return mapError(c, err)
    }
  })

  /* ---------------------------------- playbooks ---------------------------------- */

  app.get("/playbooks", requireSession(), (c) => {
    try {
      return c.json({ data: service().listPlaybooks(serviceContextOf(c)) })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.post(
    "/accounts/:id/playbooks/apply",
    requireSession(),
    zValidator("json", applyCsPlaybookSchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid request body", result.error.flatten())
    }),
    async (c) => {
      try {
        const links = await service().applyPlaybook(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        return c.json({ data: links }, 201)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/accounts/:id/playbook-tasks", requireSession(), async (c) => {
    try {
      const result = await service().listPlaybookTasks(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: result })
    } catch (err) {
      return mapError(c, err)
    }
  })

  /* --------------------------------- renewals --------------------------------- */

  app.get(
    "/renewals",
    requireSession(),
    zValidator("query", csRenewalQuerySchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid query parameters", result.error.flatten())
    }),
    async (c) => {
      try {
        const result = await service().listRenewals(serviceContextOf(c), c.req.valid("query"))
        return c.json(result)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.post(
    "/renewals",
    requireSession(),
    zValidator("json", createCsRenewalSchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid request body", result.error.flatten())
    }),
    async (c) => {
      try {
        const renewal = await service().createRenewal(serviceContextOf(c), c.req.valid("json"))
        return c.json({ data: renewal }, 201)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/renewals/:id", requireSession(), async (c) => {
    try {
      const renewal = await service().getRenewal(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: renewal })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.patch(
    "/renewals/:id",
    requireSession(),
    zValidator("json", updateCsRenewalSchema, (result, c) => {
      if (!result.success) return invalidBody(c, "Invalid request body", result.error.flatten())
    }),
    async (c) => {
      try {
        const renewal = await service().updateRenewal(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        return c.json({ data: renewal })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  return app
}

export const openApiPaths = {
  "/api/v1/customer-success/accounts": {
    get: {
      summary: "List CS accounts (cursor pagination, lifecycle filter, permission-scoped)",
      operationId: "listCsAccounts",
    },
    post: {
      summary: "Create a CS account for a company",
      operationId: "createCsAccount",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(createCsAccountSchema) } },
      },
    },
  },
  "/api/v1/customer-success/accounts/{id}": {
    get: { summary: "Get a CS account", operationId: "getCsAccount" },
    patch: {
      summary: "Update a CS account",
      operationId: "updateCsAccount",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(updateCsAccountSchema) } },
      },
    },
    delete: { summary: "Soft-delete a CS account", operationId: "deleteCsAccount" },
  },
  "/api/v1/customer-success/accounts/{id}/restore": {
    post: { summary: "Restore a soft-deleted CS account", operationId: "restoreCsAccount" },
  },
  "/api/v1/customer-success/accounts/{id}/health-scores": {
    post: {
      summary: "Recompute and store a health score for a CS account",
      operationId: "recomputeCsHealthScore",
    },
    get: {
      summary: "List health-score history for a CS account",
      operationId: "listCsHealthScores",
    },
  },
  "/api/v1/customer-success/playbooks": {
    get: { summary: "List available CS playbooks", operationId: "listCsPlaybooks" },
  },
  "/api/v1/customer-success/accounts/{id}/playbooks/apply": {
    post: {
      summary: "Apply a named playbook to a CS account (creates tasks)",
      operationId: "applyCsPlaybook",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(applyCsPlaybookSchema) } },
      },
    },
  },
  "/api/v1/customer-success/accounts/{id}/playbook-tasks": {
    get: {
      summary: "List playbook tasks applied to a CS account",
      operationId: "listCsPlaybookTasks",
    },
  },
  "/api/v1/customer-success/renewals": {
    get: {
      summary: "List renewals (cursor pagination, upcoming/risk filters, permission-scoped)",
      operationId: "listCsRenewals",
    },
    post: {
      summary: "Create a renewal for a CS account",
      operationId: "createCsRenewal",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(createCsRenewalSchema) } },
      },
    },
  },
  "/api/v1/customer-success/renewals/{id}": {
    get: { summary: "Get a renewal", operationId: "getCsRenewal" },
    patch: {
      summary: "Update a renewal",
      operationId: "updateCsRenewal",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(updateCsRenewalSchema) } },
      },
    },
  },
}

export {
  csAccountEnvelope,
  csAccountListEnvelope,
  csHealthScoreEnvelope,
  csHealthScoreListEnvelope,
  csPlaybookApplyEnvelope,
  csPlaybookListEnvelope,
  csPlaybookTaskListEnvelope,
  csRenewalEnvelope,
  csRenewalListEnvelope,
}
