// Code generated by scripts/gen-routes.ts. Do not edit by hand.
// Regenerate with: bun run scripts/gen-routes.ts (wired as `bun run gen:routes`).

import type { ModuleDefinition } from "./types"
import {
  basePath as activitiesBasePath,
  createRoutes as createActivitiesRoutes,
  openApiPaths as activitiesOpenApiPaths,
} from "./activities"
import {
  basePath as aiAgentsBasePath,
  createRoutes as createAiAgentsRoutes,
  openApiPaths as aiAgentsOpenApiPaths,
} from "./ai-agents"
import {
  basePath as aiGovernanceBasePath,
  createRoutes as createAiGovernanceRoutes,
  openApiPaths as aiGovernanceOpenApiPaths,
} from "./ai-governance"
import {
  basePath as aiBasePath,
  createRoutes as createAiRoutes,
  openApiPaths as aiOpenApiPaths,
} from "./ai"
import {
  basePath as apiWebhooksBasePath,
  createRoutes as createApiWebhooksRoutes,
  openApiPaths as apiWebhooksOpenApiPaths,
} from "./api-webhooks"
import {
  basePath as authBasePath,
  createRoutes as createAuthRoutes,
  openApiPaths as authOpenApiPaths,
} from "./auth"
import {
  basePath as automationBasePath,
  createRoutes as createAutomationRoutes,
  openApiPaths as automationOpenApiPaths,
} from "./automation"
import {
  basePath as bookingLinksBasePath,
  createRoutes as createBookingLinksRoutes,
  openApiPaths as bookingLinksOpenApiPaths,
} from "./booking-links"
import {
  basePath as calendarBasePath,
  createRoutes as createCalendarRoutes,
  openApiPaths as calendarOpenApiPaths,
} from "./calendar"
import {
  basePath as callingBasePath,
  createRoutes as createCallingRoutes,
  openApiPaths as callingOpenApiPaths,
} from "./calling"
import {
  basePath as companiesBasePath,
  createRoutes as createCompaniesRoutes,
  openApiPaths as companiesOpenApiPaths,
} from "./companies"
import {
  basePath as conversationIntelligenceBasePath,
  createRoutes as createConversationIntelligenceRoutes,
  openApiPaths as conversationIntelligenceOpenApiPaths,
} from "./conversation-intelligence"
import {
  basePath as customObjectsBasePath,
  createRoutes as createCustomObjectsRoutes,
  openApiPaths as customObjectsOpenApiPaths,
} from "./custom-objects"
import {
  basePath as customerSuccessBasePath,
  createRoutes as createCustomerSuccessRoutes,
  openApiPaths as customerSuccessOpenApiPaths,
} from "./customer-success"
import {
  basePath as dashboardsBasePath,
  createRoutes as createDashboardsRoutes,
  openApiPaths as dashboardsOpenApiPaths,
} from "./dashboards"
import {
  basePath as dealsBasePath,
  createRoutes as createDealsRoutes,
  openApiPaths as dealsOpenApiPaths,
} from "./deals"
import {
  basePath as emailBasePath,
  createRoutes as createEmailRoutes,
  openApiPaths as emailOpenApiPaths,
} from "./email"
import {
  basePath as filesBasePath,
  createRoutes as createFilesRoutes,
  openApiPaths as filesOpenApiPaths,
} from "./files"
import {
  basePath as formsBasePath,
  createRoutes as createFormsRoutes,
  openApiPaths as formsOpenApiPaths,
} from "./forms"
import {
  basePath as importExportBasePath,
  createRoutes as createImportExportRoutes,
  openApiPaths as importExportOpenApiPaths,
} from "./import-export"
import {
  basePath as integrationsBasePath,
  createRoutes as createIntegrationsRoutes,
  openApiPaths as integrationsOpenApiPaths,
} from "./integrations"
import {
  basePath as invoicesBasePath,
  createRoutes as createInvoicesRoutes,
  openApiPaths as invoicesOpenApiPaths,
} from "./invoices"
import {
  basePath as knowledgeBaseBasePath,
  createRoutes as createKnowledgeBaseRoutes,
  openApiPaths as knowledgeBaseOpenApiPaths,
} from "./knowledge-base"
import {
  basePath as leadsBasePath,
  createRoutes as createLeadsRoutes,
  openApiPaths as leadsOpenApiPaths,
} from "./leads"
import {
  basePath as marketingBasePath,
  createRoutes as createMarketingRoutes,
  openApiPaths as marketingOpenApiPaths,
} from "./marketing"
import {
  basePath as marketplaceBasePath,
  createRoutes as createMarketplaceRoutes,
  openApiPaths as marketplaceOpenApiPaths,
} from "./marketplace"
import {
  basePath as notificationsBasePath,
  createRoutes as createNotificationsRoutes,
  openApiPaths as notificationsOpenApiPaths,
} from "./notifications"
import {
  basePath as onboardingBasePath,
  createRoutes as createOnboardingRoutes,
  openApiPaths as onboardingOpenApiPaths,
} from "./onboarding"
import {
  basePath as peopleBasePath,
  createRoutes as createPeopleRoutes,
  openApiPaths as peopleOpenApiPaths,
} from "./people"
import {
  basePath as pipelinesBasePath,
  createRoutes as createPipelinesRoutes,
  openApiPaths as pipelinesOpenApiPaths,
} from "./pipelines"
import {
  basePath as portalBasePath,
  createRoutes as createPortalRoutes,
  openApiPaths as portalOpenApiPaths,
} from "./portal"
import {
  basePath as productsBasePath,
  createRoutes as createProductsRoutes,
  openApiPaths as productsOpenApiPaths,
} from "./products"
import {
  basePath as quotesBasePath,
  createRoutes as createQuotesRoutes,
  openApiPaths as quotesOpenApiPaths,
} from "./quotes"
import {
  basePath as reportsBasePath,
  createRoutes as createReportsRoutes,
  openApiPaths as reportsOpenApiPaths,
} from "./reports"
import {
  basePath as searchBasePath,
  createRoutes as createSearchRoutes,
  openApiPaths as searchOpenApiPaths,
} from "./search"
import {
  basePath as sequencesBasePath,
  createRoutes as createSequencesRoutes,
  openApiPaths as sequencesOpenApiPaths,
} from "./sequences"
import {
  basePath as settingsBasePath,
  createRoutes as createSettingsRoutes,
  openApiPaths as settingsOpenApiPaths,
} from "./settings"
import {
  basePath as supportBasePath,
  createRoutes as createSupportRoutes,
  openApiPaths as supportOpenApiPaths,
} from "./support"
import {
  basePath as systemBasePath,
  createRoutes as createSystemRoutes,
  openApiPaths as systemOpenApiPaths,
} from "./system"
import {
  basePath as tasksBasePath,
  createRoutes as createTasksRoutes,
  openApiPaths as tasksOpenApiPaths,
} from "./tasks"
import {
  basePath as unifiedInboxBasePath,
  createRoutes as createUnifiedInboxRoutes,
  openApiPaths as unifiedInboxOpenApiPaths,
} from "./unified-inbox"
import {
  basePath as whatsappBasePath,
  createRoutes as createWhatsappRoutes,
  openApiPaths as whatsappOpenApiPaths,
} from "./whatsapp"

/**
 * Module registry — the single list `routes/v1.ts` mounts. Module agents
 * add `routes/modules/<slug>.ts` files exporting `basePath`,
 * `createRoutes()` and optionally `openApiPaths`, then run the generator
 * instead of editing this file or `v1.ts` by hand.
 */
export const moduleRoutes: ModuleDefinition[] = [
  { path: activitiesBasePath, createRoutes: createActivitiesRoutes, openApiPaths: activitiesOpenApiPaths },
  { path: aiAgentsBasePath, createRoutes: createAiAgentsRoutes, openApiPaths: aiAgentsOpenApiPaths },
  { path: aiGovernanceBasePath, createRoutes: createAiGovernanceRoutes, openApiPaths: aiGovernanceOpenApiPaths },
  { path: aiBasePath, createRoutes: createAiRoutes, openApiPaths: aiOpenApiPaths },
  { path: apiWebhooksBasePath, createRoutes: createApiWebhooksRoutes, openApiPaths: apiWebhooksOpenApiPaths },
  { path: authBasePath, createRoutes: createAuthRoutes, openApiPaths: authOpenApiPaths },
  { path: automationBasePath, createRoutes: createAutomationRoutes, openApiPaths: automationOpenApiPaths },
  { path: bookingLinksBasePath, createRoutes: createBookingLinksRoutes, openApiPaths: bookingLinksOpenApiPaths },
  { path: calendarBasePath, createRoutes: createCalendarRoutes, openApiPaths: calendarOpenApiPaths },
  { path: callingBasePath, createRoutes: createCallingRoutes, openApiPaths: callingOpenApiPaths },
  { path: companiesBasePath, createRoutes: createCompaniesRoutes, openApiPaths: companiesOpenApiPaths },
  { path: conversationIntelligenceBasePath, createRoutes: createConversationIntelligenceRoutes, openApiPaths: conversationIntelligenceOpenApiPaths },
  { path: customObjectsBasePath, createRoutes: createCustomObjectsRoutes, openApiPaths: customObjectsOpenApiPaths },
  { path: customerSuccessBasePath, createRoutes: createCustomerSuccessRoutes, openApiPaths: customerSuccessOpenApiPaths },
  { path: dashboardsBasePath, createRoutes: createDashboardsRoutes, openApiPaths: dashboardsOpenApiPaths },
  { path: dealsBasePath, createRoutes: createDealsRoutes, openApiPaths: dealsOpenApiPaths },
  { path: emailBasePath, createRoutes: createEmailRoutes, openApiPaths: emailOpenApiPaths },
  { path: filesBasePath, createRoutes: createFilesRoutes, openApiPaths: filesOpenApiPaths },
  { path: formsBasePath, createRoutes: createFormsRoutes, openApiPaths: formsOpenApiPaths },
  { path: importExportBasePath, createRoutes: createImportExportRoutes, openApiPaths: importExportOpenApiPaths },
  { path: integrationsBasePath, createRoutes: createIntegrationsRoutes, openApiPaths: integrationsOpenApiPaths },
  { path: invoicesBasePath, createRoutes: createInvoicesRoutes, openApiPaths: invoicesOpenApiPaths },
  { path: knowledgeBaseBasePath, createRoutes: createKnowledgeBaseRoutes, openApiPaths: knowledgeBaseOpenApiPaths },
  { path: leadsBasePath, createRoutes: createLeadsRoutes, openApiPaths: leadsOpenApiPaths },
  { path: marketingBasePath, createRoutes: createMarketingRoutes, openApiPaths: marketingOpenApiPaths },
  { path: marketplaceBasePath, createRoutes: createMarketplaceRoutes, openApiPaths: marketplaceOpenApiPaths },
  { path: notificationsBasePath, createRoutes: createNotificationsRoutes, openApiPaths: notificationsOpenApiPaths },
  { path: onboardingBasePath, createRoutes: createOnboardingRoutes, openApiPaths: onboardingOpenApiPaths },
  { path: peopleBasePath, createRoutes: createPeopleRoutes, openApiPaths: peopleOpenApiPaths },
  { path: pipelinesBasePath, createRoutes: createPipelinesRoutes, openApiPaths: pipelinesOpenApiPaths },
  { path: portalBasePath, createRoutes: createPortalRoutes, openApiPaths: portalOpenApiPaths },
  { path: productsBasePath, createRoutes: createProductsRoutes, openApiPaths: productsOpenApiPaths },
  { path: quotesBasePath, createRoutes: createQuotesRoutes, openApiPaths: quotesOpenApiPaths },
  { path: reportsBasePath, createRoutes: createReportsRoutes, openApiPaths: reportsOpenApiPaths },
  { path: searchBasePath, createRoutes: createSearchRoutes, openApiPaths: searchOpenApiPaths },
  { path: sequencesBasePath, createRoutes: createSequencesRoutes, openApiPaths: sequencesOpenApiPaths },
  { path: settingsBasePath, createRoutes: createSettingsRoutes, openApiPaths: settingsOpenApiPaths },
  { path: supportBasePath, createRoutes: createSupportRoutes, openApiPaths: supportOpenApiPaths },
  { path: systemBasePath, createRoutes: createSystemRoutes, openApiPaths: systemOpenApiPaths },
  { path: tasksBasePath, createRoutes: createTasksRoutes, openApiPaths: tasksOpenApiPaths },
  { path: unifiedInboxBasePath, createRoutes: createUnifiedInboxRoutes, openApiPaths: unifiedInboxOpenApiPaths },
  { path: whatsappBasePath, createRoutes: createWhatsappRoutes, openApiPaths: whatsappOpenApiPaths },
]
