// Code generated by scripts/gen-routes.ts. Do not edit by hand.
// Regenerate with: bun run scripts/gen-routes.ts (wired as `bun run gen:routes`).

import type { ModuleDefinition } from "./types"
import {
  basePath as activitiesBasePath,
  createRoutes as createActivitiesRoutes,
  openApiPaths as activitiesOpenApiPaths,
} from "./activities"
import {
  basePath as aiGovernanceBasePath,
  createRoutes as createAiGovernanceRoutes,
  openApiPaths as aiGovernanceOpenApiPaths,
} from "./ai-governance"
import {
  basePath as aiBasePath,
  createRoutes as createAiRoutes,
  openApiPaths as aiOpenApiPaths,
} from "./ai"
import {
  basePath as authBasePath,
  createRoutes as createAuthRoutes,
  openApiPaths as authOpenApiPaths,
} from "./auth"
import {
  basePath as automationBasePath,
  createRoutes as createAutomationRoutes,
  openApiPaths as automationOpenApiPaths,
} from "./automation"
import {
  basePath as calendarBasePath,
  createRoutes as createCalendarRoutes,
  openApiPaths as calendarOpenApiPaths,
} from "./calendar"
import {
  basePath as callingBasePath,
  createRoutes as createCallingRoutes,
  openApiPaths as callingOpenApiPaths,
} from "./calling"
import {
  basePath as companiesBasePath,
  createRoutes as createCompaniesRoutes,
  openApiPaths as companiesOpenApiPaths,
} from "./companies"
import {
  basePath as customObjectsBasePath,
  createRoutes as createCustomObjectsRoutes,
  openApiPaths as customObjectsOpenApiPaths,
} from "./custom-objects"
import {
  basePath as dashboardsBasePath,
  createRoutes as createDashboardsRoutes,
  openApiPaths as dashboardsOpenApiPaths,
} from "./dashboards"
import {
  basePath as dealsBasePath,
  createRoutes as createDealsRoutes,
  openApiPaths as dealsOpenApiPaths,
} from "./deals"
import {
  basePath as emailBasePath,
  createRoutes as createEmailRoutes,
  openApiPaths as emailOpenApiPaths,
} from "./email"
import {
  basePath as filesBasePath,
  createRoutes as createFilesRoutes,
  openApiPaths as filesOpenApiPaths,
} from "./files"
import {
  basePath as formsBasePath,
  createRoutes as createFormsRoutes,
  openApiPaths as formsOpenApiPaths,
} from "./forms"
import {
  basePath as importExportBasePath,
  createRoutes as createImportExportRoutes,
  openApiPaths as importExportOpenApiPaths,
} from "./import-export"
import {
  basePath as integrationsBasePath,
  createRoutes as createIntegrationsRoutes,
  openApiPaths as integrationsOpenApiPaths,
} from "./integrations"
import {
  basePath as invoicesBasePath,
  createRoutes as createInvoicesRoutes,
  openApiPaths as invoicesOpenApiPaths,
} from "./invoices"
import {
  basePath as leadsBasePath,
  createRoutes as createLeadsRoutes,
  openApiPaths as leadsOpenApiPaths,
} from "./leads"
import {
  basePath as peopleBasePath,
  createRoutes as createPeopleRoutes,
  openApiPaths as peopleOpenApiPaths,
} from "./people"
import {
  basePath as pipelinesBasePath,
  createRoutes as createPipelinesRoutes,
  openApiPaths as pipelinesOpenApiPaths,
} from "./pipelines"
import {
  basePath as productsBasePath,
  createRoutes as createProductsRoutes,
  openApiPaths as productsOpenApiPaths,
} from "./products"
import {
  basePath as quotesBasePath,
  createRoutes as createQuotesRoutes,
  openApiPaths as quotesOpenApiPaths,
} from "./quotes"
import {
  basePath as reportsBasePath,
  createRoutes as createReportsRoutes,
  openApiPaths as reportsOpenApiPaths,
} from "./reports"
import {
  basePath as searchBasePath,
  createRoutes as createSearchRoutes,
  openApiPaths as searchOpenApiPaths,
} from "./search"
import {
  basePath as systemBasePath,
  createRoutes as createSystemRoutes,
  openApiPaths as systemOpenApiPaths,
} from "./system"
import {
  basePath as tasksBasePath,
  createRoutes as createTasksRoutes,
  openApiPaths as tasksOpenApiPaths,
} from "./tasks"
import {
  basePath as unifiedInboxBasePath,
  createRoutes as createUnifiedInboxRoutes,
  openApiPaths as unifiedInboxOpenApiPaths,
} from "./unified-inbox"
import {
  basePath as whatsappBasePath,
  createRoutes as createWhatsappRoutes,
  openApiPaths as whatsappOpenApiPaths,
} from "./whatsapp"

/**
 * Module registry — the single list `routes/v1.ts` mounts. Module agents
 * add `routes/modules/<slug>.ts` files exporting `basePath`,
 * `createRoutes()` and optionally `openApiPaths`, then run the generator
 * instead of editing this file or `v1.ts` by hand.
 */
export const moduleRoutes: ModuleDefinition[] = [
  { path: activitiesBasePath, createRoutes: createActivitiesRoutes, openApiPaths: activitiesOpenApiPaths },
  { path: aiGovernanceBasePath, createRoutes: createAiGovernanceRoutes, openApiPaths: aiGovernanceOpenApiPaths },
  { path: aiBasePath, createRoutes: createAiRoutes, openApiPaths: aiOpenApiPaths },
  { path: authBasePath, createRoutes: createAuthRoutes, openApiPaths: authOpenApiPaths },
  { path: automationBasePath, createRoutes: createAutomationRoutes, openApiPaths: automationOpenApiPaths },
  { path: calendarBasePath, createRoutes: createCalendarRoutes, openApiPaths: calendarOpenApiPaths },
  { path: callingBasePath, createRoutes: createCallingRoutes, openApiPaths: callingOpenApiPaths },
  { path: companiesBasePath, createRoutes: createCompaniesRoutes, openApiPaths: companiesOpenApiPaths },
  { path: customObjectsBasePath, createRoutes: createCustomObjectsRoutes, openApiPaths: customObjectsOpenApiPaths },
  { path: dashboardsBasePath, createRoutes: createDashboardsRoutes, openApiPaths: dashboardsOpenApiPaths },
  { path: dealsBasePath, createRoutes: createDealsRoutes, openApiPaths: dealsOpenApiPaths },
  { path: emailBasePath, createRoutes: createEmailRoutes, openApiPaths: emailOpenApiPaths },
  { path: filesBasePath, createRoutes: createFilesRoutes, openApiPaths: filesOpenApiPaths },
  { path: formsBasePath, createRoutes: createFormsRoutes, openApiPaths: formsOpenApiPaths },
  { path: importExportBasePath, createRoutes: createImportExportRoutes, openApiPaths: importExportOpenApiPaths },
  { path: integrationsBasePath, createRoutes: createIntegrationsRoutes, openApiPaths: integrationsOpenApiPaths },
  { path: invoicesBasePath, createRoutes: createInvoicesRoutes, openApiPaths: invoicesOpenApiPaths },
  { path: leadsBasePath, createRoutes: createLeadsRoutes, openApiPaths: leadsOpenApiPaths },
  { path: peopleBasePath, createRoutes: createPeopleRoutes, openApiPaths: peopleOpenApiPaths },
  { path: pipelinesBasePath, createRoutes: createPipelinesRoutes, openApiPaths: pipelinesOpenApiPaths },
  { path: productsBasePath, createRoutes: createProductsRoutes, openApiPaths: productsOpenApiPaths },
  { path: quotesBasePath, createRoutes: createQuotesRoutes, openApiPaths: quotesOpenApiPaths },
  { path: reportsBasePath, createRoutes: createReportsRoutes, openApiPaths: reportsOpenApiPaths },
  { path: searchBasePath, createRoutes: createSearchRoutes, openApiPaths: searchOpenApiPaths },
  { path: systemBasePath, createRoutes: createSystemRoutes, openApiPaths: systemOpenApiPaths },
  { path: tasksBasePath, createRoutes: createTasksRoutes, openApiPaths: tasksOpenApiPaths },
  { path: unifiedInboxBasePath, createRoutes: createUnifiedInboxRoutes, openApiPaths: unifiedInboxOpenApiPaths },
  { path: whatsappBasePath, createRoutes: createWhatsappRoutes, openApiPaths: whatsappOpenApiPaths },
]
