import { zValidator } from "@hono/zod-validator"
import { roleInWorkspace, type Session } from "@yourcrm/auth"
import {
  createEmailService,
  type EmailOutboundConnectionRecord,
  type EmailService,
  type EmailTransportPort,
} from "@yourcrm/crm/src/email"
import {
  createSalesSequenceSchema,
  createSalesSequenceService,
  describeSalesSequenceCatalogue,
  enrollInSalesSequenceSchema,
  replaceSalesSequenceStepsSchema,
  salesSequenceEnrollmentQuerySchema,
  salesSequenceEnrollmentSchema,
  salesSequenceQuerySchema,
  salesSequenceSchema,
  salesSequenceStatusSchema,
  stopSalesSequenceEnrollmentSchema,
  subscribeSalesSequenceExits,
  unsubscribeFromSalesSequencesSchema,
  updateSalesSequenceSchema,
  type SalesSequenceService,
  type SalesSequenceStepExecutorPort,
  type SalesSequenceStepJobRequest,
} from "@yourcrm/crm/src/sequences"
import { createTasksService, type TasksService } from "@yourcrm/crm/src/tasks"
import { getDb, writeAudit } from "@yourcrm/database"
import {
  createEmailRepository,
  type CreateEmailMessageInput,
  type CreateEmailThreadInput,
  type UpdateEmailMessageInput,
  type UpdateEmailThreadInput,
} from "@yourcrm/database/src/repositories/email-repository"
import { createIntegrationsRepository } from "@yourcrm/database/src/repositories/integrations-repository"
import { createPeopleRepository } from "@yourcrm/database/src/repositories/people-repository"
import {
  createSalesSequencesRepository,
  type CreateSalesSequenceInput,
  type UpdateSalesSequenceInput,
} from "@yourcrm/database/src/repositories/sequences-repository"
import {
  createTasksRepository,
  type CreateTaskInput,
  type UpdateTaskInput,
} from "@yourcrm/database/src/repositories/tasks-repository"
import { listMembershipsForUser } from "@yourcrm/database/src/schema/auth"
import { getEventBus } from "@yourcrm/events"
import { getIntegrationProviderRegistry } from "@yourcrm/integrations"
import type { IntegrationProvider } from "@yourcrm/integrations"
import { PermissionDeniedError } from "@yourcrm/permissions"
import { errorEnvelope, paginatedEnvelopeSchema } from "@yourcrm/validation"
import { Hono } from "hono"
import type { Context } from "hono"
import { z } from "zod"
import type { AppEnv } from "../../hono-env"
import { requireSession } from "../../middleware/auth"
import { zodToJsonSchema } from "../../openapi/zod-to-json-schema"

/**
 * Sales engagement / sequences module (spec 47-sales-engagement, P0).
 *
 * Thin HTTP layer only: zod validation at the boundary, session from the
 * auth middleware, then straight into the domain service. The interesting
 * parts — exit conditions, step idempotency, permission inheritance — all
 * live in `@yourcrm/crm/src/sequences`; this file only BINDS them:
 *
 *   store            -> sequences repository (migration 0270)
 *   audit            -> writeAudit
 *   resolveActorRole -> the memberships table (the owner's LIVE role)
 *   resolveContact   -> the people repository (never an invented address)
 *   queue            -> the sequence-step queue seam
 *   executor         -> the EMAIL and TASKS domain services, so no business
 *                       rule is duplicated here
 *
 * REGISTRY. `routes/modules/index.ts` is generated by `bun run gen:routes`;
 * this agent must not edit or regenerate it, so the integrator's generator
 * run is what mounts `/api/v1/sequences`. The exports below (`basePath`,
 * `createRoutes`, `openApiPaths`) are the contract that generator reads.
 *
 * INTEGRATION NOTES (both are dependency blockers an agent may not fix,
 * because they require editing `package.json` or another module's file):
 *
 *  1. `@yourcrm/api` cannot import `bullmq`, so `defaultQueue()` records
 *     the enqueue as a structured log line instead of pushing to BullMQ,
 *     and enrollments sit at their current step. `apps/worker` already
 *     registers the handler (`sequence.step`); swapping in the real
 *     adapter is a four-line change in one function — nothing else moves.
 *     Identical to `automation.ts`'s `defaultQueue()`.
 *  2. `defaultEmailService()` below duplicates `email.ts`'s private
 *     `defaultService()` composition, because that module exports no
 *     factory and this agent may not edit its file. It is wiring, not
 *     logic — every rule still lives in `createEmailService` — but the
 *     integrator should export one shared factory and delete this copy.
 */

export const basePath = "/sequences"

const sequenceEnvelope = z.object({ data: salesSequenceSchema.passthrough() })
const sequenceListEnvelope = paginatedEnvelopeSchema(salesSequenceSchema.passthrough())
const enrollmentListEnvelope = paginatedEnvelopeSchema(salesSequenceEnrollmentSchema.passthrough())

export type SequencesRouteDeps = {
  service?: SalesSequenceService
}

const setStatusSchema = z.object({ status: salesSequenceStatusSchema })

/**
 * Queue binding. The domain service only knows
 * `SalesSequenceStepQueuePort`; the worker half (job name, payload schema,
 * deterministic job id) lives in `apps/worker/src/jobs/sequences.ts`.
 *
 * Replace the body with, once `bullmq` is a declared dependency of
 * `@yourcrm/api`:
 *
 * ```ts
 * await getQueue(QueueNames.Communications).add(SEQUENCE_STEP_JOB_NAME, request, {
 *   jobId: sequenceStepJobId(request),
 *   delay: Math.max(0, (request.runAt?.getTime() ?? 0) - Date.now()),
 * })
 * ```
 */
function defaultQueue() {
  return {
    enqueueSequenceStep: async (request: SalesSequenceStepJobRequest): Promise<void> => {
      console.log(
        JSON.stringify({
          level: "info",
          msg: "sequence_step_enqueued",
          job: "sequence.step",
          jobId: `sequence.step:${request.workspaceId}:${request.enrollmentId}:${request.stepIndex}`,
          sequenceId: request.sequenceId,
          stepIndex: request.stepIndex,
          runAt: request.runAt?.toISOString() ?? null,
          ...(request.correlationId === undefined ? {} : { correlationId: request.correlationId }),
        }),
      )
    },
  }
}

/** A registered provider that can also put mail on the wire. */
function emailTransportOf(provider: IntegrationProvider | null): EmailTransportPort | null {
  if (!provider) return null
  const candidate = provider as unknown as { sendEmail?: unknown }
  if (typeof candidate.sendEmail !== "function") return null
  return provider as unknown as EmailTransportPort
}

/**
 * See INTEGRATION NOTE 2 — a copy of `email.ts`'s composition, not of its
 * rules. Threading, sanitisation, the `send_external` check, the audit row
 * and the `email.sent` event all still come from `createEmailService`.
 */
function defaultEmailService(): EmailService {
  const db = getDb()
  const repository = createEmailRepository()
  const integrations = createIntegrationsRepository()
  const registry = getIntegrationProviderRegistry()
  const sendableProviderIds = (): Set<string> =>
    new Set(registry.byCapability("email.send").map((provider) => provider.id))

  return createEmailService({
    threads: {
      list: (workspaceId, query) =>
        repository.searchThreads(db, {
          workspaceId,
          limit: query.limit,
          cursor: query.cursor,
          order: query.order,
          query: query.query,
          status: query.status,
          personId: query.personId,
          companyId: query.companyId,
          dealId: query.dealId,
        }),
      findById: (workspaceId, id) => repository.findThreadById(db, workspaceId, id),
      findWithMessages: (workspaceId, id) => repository.findThreadWithMessages(db, workspaceId, id),
      create: (workspaceId, input, actorId) =>
        repository.createThread(
          db,
          workspaceId,
          input as unknown as CreateEmailThreadInput,
          actorId,
        ),
      update: (workspaceId, id, patch, actorId) =>
        repository.updateThread(
          db,
          workspaceId,
          id,
          patch as unknown as UpdateEmailThreadInput,
          actorId,
        ),
      refreshCounters: (workspaceId, threadId, lastMessageAt) =>
        repository.refreshThreadCounters(db, workspaceId, threadId, lastMessageAt),
      softDelete: async (workspaceId, id, actorId) => {
        await repository.softDelete(db, workspaceId, id, actorId)
      },
      findThreadIdsByMessageIds: (workspaceId, messageIds) =>
        repository.findThreadIdsByMessageIds(db, workspaceId, messageIds),
      findThreadByMatch: (workspaceId, match) =>
        repository.findThreadByMatch(db, workspaceId, match),
    },
    messages: {
      create: (workspaceId, input, actorId) =>
        repository.createMessage(
          db,
          workspaceId,
          input as unknown as CreateEmailMessageInput,
          actorId,
        ),
      update: (workspaceId, id, patch, actorId) =>
        repository.updateMessage(
          db,
          workspaceId,
          id,
          patch as unknown as UpdateEmailMessageInput,
          actorId,
        ),
      findById: (workspaceId, id) => repository.findMessageById(db, workspaceId, id),
      findByMessageId: (workspaceId, messageId) =>
        repository.findMessageByMessageId(db, workspaceId, messageId),
      findWithDetail: (workspaceId, id) => repository.findMessageWithDetail(db, workspaceId, id),
    },
    connections: {
      findSendable: async (workspaceId, connectionId) => {
        const sendable = sendableProviderIds()
        const toRecord = (row: {
          id: string
          providerId: string
          status: string
          config: Record<string, unknown>
        }): EmailOutboundConnectionRecord | null => {
          if (row.status !== "connected" || !sendable.has(row.providerId)) return null
          return { id: row.id, providerId: row.providerId, config: row.config }
        }
        if (connectionId !== null && connectionId !== undefined) {
          const row = await integrations.findConnectionById(db, workspaceId, connectionId)
          return row ? toRecord(row) : null
        }
        const listed = await integrations.listConnections(db, {
          workspaceId,
          limit: 50,
          status: "connected",
        })
        for (const row of listed.data) {
          const record = toRecord(row)
          if (record) return record
        }
        return null
      },
    },
    secrets: {
      readApiKey: (workspaceId, connectionId) =>
        integrations.readCredentialSecret(db, workspaceId, connectionId, "api_key"),
    },
    transports: { get: (providerId) => emailTransportOf(registry.get(providerId)) },
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "automation" })
    },
    events: getEventBus(),
  })
}

function defaultTasksService(): TasksService {
  const db = getDb()
  const repository = createTasksRepository()
  return createTasksService({
    store: {
      list: (workspaceId, query) => repository.search(db, { workspaceId, ...query }),
      findById: (workspaceId, id) => repository.findById(db, workspaceId, id),
      create: (workspaceId, input, actorId) =>
        repository.create(db, workspaceId, input as unknown as CreateTaskInput, actorId),
      update: (workspaceId, id, input, actorId) =>
        repository.update(db, workspaceId, id, input as unknown as UpdateTaskInput, actorId),
      softDelete: async (workspaceId, id, actorId) => {
        await repository.softDelete(db, workspaceId, id, actorId)
      },
      restore: async (workspaceId, id) => {
        await repository.restore(db, workspaceId, id)
      },
    },
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "automation" })
    },
    events: getEventBus(),
  })
}

/**
 * Step bindings. Every step reaches the owning module through that
 * module's own DOMAIN SERVICE, which means the owner's permission is
 * re-checked there (`send_external` for a send, `task:create` for a task)
 * on top of the check this engine already made, and the owning module
 * emits its own event and writes its own audit row. An automated send is
 * therefore indistinguishable from a hand-sent one downstream — except
 * that it is attributable.
 */
function defaultExecutor(): SalesSequenceStepExecutorPort {
  const email = defaultEmailService()
  const tasks = defaultTasksService()

  return {
    sendSequenceEmail: async (ctx, input) => {
      const sent = await email.sendMessage(ctx, {
        to: [{ address: input.to }],
        subject: input.subject,
        bodyText: input.bodyText,
        bodyHtml: input.bodyHtml ?? null,
        // Reply into the existing thread from step 2 onwards, so the
        // prospect sees one conversation, not five cold emails.
        threadId: input.threadId ?? null,
        personId: input.personId ?? null,
        dealId: input.dealId ?? null,
      })
      return {
        messageId: String(sent.message.id),
        threadId: String(sent.message.threadId),
      }
    },

    createSequenceTask: async (ctx, input) => {
      const task = await tasks.create(ctx, {
        title: input.title,
        description: input.description ?? null,
        priority: input.priority ?? null,
        dueDate: input.dueDate ?? null,
        assigneeId: input.assigneeId ?? null,
        ...(input.personId === null || input.personId === undefined
          ? {}
          : { personId: input.personId }),
        ...(input.dealId === null || input.dealId === undefined ? {} : { dealId: input.dealId }),
      })
      return { taskId: String(task.id) }
    },
  }
}

function defaultService(): SalesSequenceService {
  const db = getDb()
  const repository = createSalesSequencesRepository()
  const people = createPeopleRepository()

  return createSalesSequenceService({
    store: {
      list: (workspaceId, query) =>
        repository.search(db, {
          workspaceId,
          limit: query.limit,
          cursor: query.cursor,
          order: query.order,
          query: query.query,
          status: query.status,
          ownerId: query.ownerId,
        }),
      findById: (workspaceId, id) => repository.findById(db, workspaceId, id),
      create: (workspaceId, input, actorId) =>
        repository.create(db, workspaceId, input as unknown as CreateSalesSequenceInput, actorId),
      update: (workspaceId, id, input, actorId) =>
        repository.update(
          db,
          workspaceId,
          id,
          input as unknown as UpdateSalesSequenceInput,
          actorId,
        ),
      softDelete: async (workspaceId, id, actorId) => {
        await repository.softDelete(db, workspaceId, id, actorId)
      },
      restore: async (workspaceId, id) => {
        await repository.restore(db, workspaceId, id)
      },
      markEnrolled: async (workspaceId, id) => {
        await repository.markEnrolled(db, workspaceId, id)
      },

      listSteps: (workspaceId, sequenceId) => repository.listSteps(db, workspaceId, sequenceId),
      replaceSteps: (workspaceId, sequenceId, steps, actorId) =>
        repository.replaceSteps(db, workspaceId, sequenceId, steps, actorId),

      enrollPerson: (workspaceId, input) =>
        repository.enrollPerson(db, workspaceId, {
          sequenceId: String(input.sequenceId),
          personId: String(input.personId),
          dealId: (input.dealId as string | null) ?? null,
          emailAddress: String(input.emailAddress),
          enrolledBy: (input.enrolledBy as string | null) ?? null,
          nextRunAt: (input.nextRunAt as Date | null) ?? null,
        }),
      findEnrollmentById: (workspaceId, id) => repository.findEnrollmentById(db, workspaceId, id),
      listEnrollments: (workspaceId, query) =>
        repository.searchEnrollments(db, {
          workspaceId,
          limit: query.limit,
          cursor: query.cursor,
          order: query.order,
          sequenceId: query.sequenceId,
          personId: query.personId,
          status: query.status,
          exitReason: query.exitReason,
        }),
      updateEnrollment: (workspaceId, id, patch) =>
        repository.updateEnrollment(db, workspaceId, id, patch),
      incrementSentCount: (workspaceId, id) => repository.incrementSentCount(db, workspaceId, id),
      findActiveEnrollmentsByTarget: (workspaceId, target) =>
        repository.findActiveEnrollmentsByTarget(db, workspaceId, target),
      findSuppression: (workspaceId, target) => repository.findSuppression(db, workspaceId, target),

      claimStepRun: (workspaceId, input) => repository.claimStepRun(db, workspaceId, input),
      completeStepRun: (workspaceId, id, patch) =>
        repository.completeStepRun(db, workspaceId, id, patch),
      listStepRuns: (workspaceId, enrollmentId) =>
        repository.listStepRuns(db, workspaceId, enrollmentId),

      stats: (workspaceId, sequenceId) => repository.sequenceStats(db, workspaceId, sequenceId),
    },
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "user" })
    },
    queue: defaultQueue(),
    executor: defaultExecutor(),
    // PERMISSION INHERITANCE: the owner's role is read from memberships at
    // execution time, so a demotion or removal takes effect on the next step.
    resolveActorRole: async (workspaceId, actorId) => {
      const memberships = await listMembershipsForUser(db, actorId)
      const membership = memberships.find((m) => m.workspaceId === workspaceId)
      return membership ? (membership.role ?? "viewer") : null
    },
    // The recipient comes from the PEOPLE module's own contract. A
    // sequence never invents an address.
    resolveContact: async (workspaceId, personId) => {
      const found = await people.findWithContacts(db, workspaceId, personId)
      if (!found) return null
      const primary = found.emails.find((row) => row.isPrimary) ?? found.emails[0]
      return { personId, emailAddress: primary ? String(primary.email) : null }
    },
  })
}

/**
 * Process-wide service for machine callers (the exit watcher). The HTTP
 * handlers use their own lazily-built instance, or an injected fake.
 */
let moduleService: SalesSequenceService | null = null
const resolveModuleService = (): SalesSequenceService => (moduleService ??= defaultService())

function serviceContextOf(c: Context<AppEnv>) {
  const session = c.get("session") as Session | null
  return {
    workspaceId: session?.workspaceId ?? "",
    actorId: session?.user.id ?? "",
    role: session ? roleInWorkspace(session) : "viewer",
    correlationId: c.get("requestId") as string | undefined,
  }
}

const STATUS_BY_CODE: Record<string, 400 | 403 | 404 | 409 | 422> = {
  NOT_FOUND: 404,
  INVALID_SEQUENCE: 400,
  SEQUENCE_NOT_ENROLLABLE: 422,
  SEQUENCE_CONTACT_SUPPRESSED: 409,
  SEQUENCE_STEP_FAILED: 422,
}

function mapError(c: Context<AppEnv>, err: unknown) {
  const requestId = c.get("requestId") as string | undefined
  if (err instanceof PermissionDeniedError) {
    return c.json(errorEnvelope("FORBIDDEN", err.message, requestId), 403)
  }
  if (err instanceof z.ZodError) {
    return c.json(
      errorEnvelope("VALIDATION_ERROR", "Invalid request body", requestId, err.flatten()),
      400,
    )
  }
  if (err instanceof Error) {
    const code = (err as { code?: string }).code
    const status = code ? STATUS_BY_CODE[code] : undefined
    if (code && status) return c.json(errorEnvelope(code, err.message, requestId), status)
  }
  throw err
}

function invalidBody(c: Context, result: { error: { flatten(): unknown } }) {
  return c.json(
    errorEnvelope(
      "VALIDATION_ERROR",
      "Invalid request body",
      c.req.header("x-request-id") ?? undefined,
      result.error.flatten(),
    ),
    400,
  )
}

function invalidQuery(c: Context, result: { error: { flatten(): unknown } }) {
  return c.json(
    errorEnvelope(
      "VALIDATION_ERROR",
      "Invalid query parameters",
      c.req.header("x-request-id") ?? undefined,
      result.error.flatten(),
    ),
    400,
  )
}

export function createRoutes(deps: SequencesRouteDeps = {}) {
  const app = new Hono<AppEnv>()
  // Lazy default wiring: route construction must never touch the database —
  // registry and full-app tests mount every module without a live Postgres.
  let cached: SalesSequenceService | null = deps.service ?? null
  const service = () => (cached ??= resolveModuleService())

  // Static segments first: `/catalogue`, `/enrollments` and `/unsubscribe`
  // must not be swallowed by `/:id`.
  app.get("/catalogue", requireSession(), (c) => c.json({ data: describeSalesSequenceCatalogue() }))

  app.get(
    "/enrollments",
    requireSession(),
    zValidator("query", salesSequenceEnrollmentQuerySchema, (result, c) => {
      if (!result.success) return invalidQuery(c, result)
    }),
    async (c) => {
      try {
        return c.json(await service().listEnrollments(serviceContextOf(c), c.req.valid("query")))
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/enrollments/:enrollmentId", requireSession(), async (c) => {
    try {
      const detail = await service().getEnrollment(serviceContextOf(c), c.req.param("enrollmentId"))
      return c.json({ data: { ...detail.enrollment, runs: detail.runs } })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.post("/enrollments/:enrollmentId/pause", requireSession(), async (c) => {
    try {
      const paused = await service().pauseEnrollment(
        serviceContextOf(c),
        c.req.param("enrollmentId"),
      )
      return c.json({ data: paused })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.post("/enrollments/:enrollmentId/resume", requireSession(), async (c) => {
    try {
      const resumed = await service().resumeEnrollment(
        serviceContextOf(c),
        c.req.param("enrollmentId"),
      )
      return c.json({ data: resumed })
    } catch (err) {
      return mapError(c, err)
    }
  })

  // Removing somebody is a STOP, not a delete: the enrollment stays, with
  // the reason it ended, so the audit trail survives.
  app.post(
    "/enrollments/:enrollmentId/stop",
    requireSession(),
    zValidator("json", stopSalesSequenceEnrollmentSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const stopped = await service().stopEnrollment(
          serviceContextOf(c),
          c.req.param("enrollmentId"),
          c.req.valid("json"),
        )
        return c.json({ data: stopped })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  // Workspace-wide opt-out: stops every live drip for this contact and
  // blocks re-enrolment anywhere.
  app.post(
    "/unsubscribe",
    requireSession(),
    zValidator("json", unsubscribeFromSalesSequencesSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        return c.json({
          data: await service().unsubscribe(serviceContextOf(c), c.req.valid("json")),
        })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get(
    "/",
    requireSession(),
    zValidator("query", salesSequenceQuerySchema, (result, c) => {
      if (!result.success) return invalidQuery(c, result)
    }),
    async (c) => {
      try {
        return c.json(await service().list(serviceContextOf(c), c.req.valid("query")))
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.post(
    "/",
    requireSession(),
    zValidator("json", createSalesSequenceSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const sequence = await service().create(serviceContextOf(c), c.req.valid("json"))
        return c.json({ data: sequence }, 201)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/:id", requireSession(), async (c) => {
    try {
      const detail = await service().get(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: { ...detail.sequence, steps: detail.steps } })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.patch(
    "/:id",
    requireSession(),
    zValidator("json", updateSalesSequenceSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const sequence = await service().update(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        return c.json({ data: sequence })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.delete("/:id", requireSession(), async (c) => {
    try {
      await service().softDelete(serviceContextOf(c), c.req.param("id"))
      return c.json({ data: { deleted: true } })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.post("/:id/restore", requireSession(), async (c) => {
    try {
      return c.json({ data: await service().restore(serviceContextOf(c), c.req.param("id")) })
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.put(
    "/:id/steps",
    requireSession(),
    zValidator("json", replaceSalesSequenceStepsSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const steps = await service().replaceSteps(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        return c.json({ data: steps })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  // Activating needs `send_external` — it is what makes the sequence start
  // sending. Pausing only needs `update`. See the service's `access.ts`.
  app.post(
    "/:id/status",
    requireSession(),
    zValidator("json", setStatusSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const sequence = await service().setStatus(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json").status,
        )
        return c.json({ data: sequence })
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.post(
    "/:id/enrollments",
    requireSession(),
    zValidator("json", enrollInSalesSequenceSchema, (result, c) => {
      if (!result.success) return invalidBody(c, result)
    }),
    async (c) => {
      try {
        const result = await service().enroll(
          serviceContextOf(c),
          c.req.param("id"),
          c.req.valid("json"),
        )
        // 200 rather than 201 when the person was already enrolled: the
        // call is idempotent and created nothing.
        return c.json({ data: result.enrollment }, result.created ? 201 : 200)
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/:id/enrollments", requireSession(), async (c) => {
    try {
      return c.json(
        await service().listEnrollments(serviceContextOf(c), { sequenceId: c.req.param("id") }),
      )
    } catch (err) {
      return mapError(c, err)
    }
  })

  app.get("/:id/stats", requireSession(), async (c) => {
    try {
      return c.json({ data: await service().stats(serviceContextOf(c), c.req.param("id")) })
    } catch (err) {
      return mapError(c, err)
    }
  })

  return app
}

/**
 * Bootstrap hook: connect the in-process event bus to the exit watcher, so
 * an inbound reply or bounce actually stops the drip. Call it ONCE from
 * `apps/api/src/index.ts`; route factories must not subscribe (see the
 * file header).
 *
 * Without this call the module still stops on unsubscribe and on manual
 * removal, but NOT on reply — which is the one thing it must do. It is the
 * single most important line of the integration.
 */
export function subscribeSalesSequenceExitWatcher(service?: SalesSequenceService): () => void {
  // Resolve the service lazily, on the first event — NOT at boot. A
  // default parameter of `defaultService()` evaluates immediately, which
  // calls getDb() during module bootstrap and crashes the API before it
  // can serve anything. Every other module defers construction the same way.
  let resolved: SalesSequenceService | undefined = service
  const lazy = new Proxy({} as SalesSequenceService, {
    get(_t, prop: string | symbol) {
      resolved ??= resolveModuleService()
      return Reflect.get(resolved as object, prop, resolved)
    },
  })
  return subscribeSalesSequenceExits(getEventBus(), lazy, (err) => {
    console.error(
      JSON.stringify({ level: "error", msg: "sequence_exit_check_failed", err: String(err) }),
    )
  })
}

export const openApiPaths = {
  "/api/v1/sequences": {
    get: {
      summary: "List sequences (search, status and owner filters)",
      operationId: "listSalesSequences",
    },
    post: {
      summary: "Create a sequence (always created as a draft)",
      operationId: "createSalesSequence",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(createSalesSequenceSchema) } },
      },
    },
  },
  "/api/v1/sequences/catalogue": {
    get: {
      summary: "Step types, limits and the exit reasons the engine produces",
      operationId: "getSalesSequenceCatalogue",
    },
  },
  "/api/v1/sequences/enrollments": {
    get: {
      summary: "Workspace-wide enrollment list",
      operationId: "listSalesSequenceEnrollments",
    },
  },
  "/api/v1/sequences/enrollments/{enrollmentId}": {
    get: {
      summary: "One enrollment with its per-step run history",
      operationId: "getSalesSequenceEnrollment",
    },
  },
  "/api/v1/sequences/enrollments/{enrollmentId}/pause": {
    post: { summary: "Pause one enrollment", operationId: "pauseSalesSequenceEnrollment" },
  },
  "/api/v1/sequences/enrollments/{enrollmentId}/resume": {
    post: { summary: "Resume a paused enrollment", operationId: "resumeSalesSequenceEnrollment" },
  },
  "/api/v1/sequences/enrollments/{enrollmentId}/stop": {
    post: {
      summary: "Stop an enrollment (removed or unsubscribed)",
      operationId: "stopSalesSequenceEnrollment",
      requestBody: {
        content: {
          "application/json": { schema: zodToJsonSchema(stopSalesSequenceEnrollmentSchema) },
        },
      },
    },
  },
  "/api/v1/sequences/unsubscribe": {
    post: {
      summary: "Workspace-wide opt-out: stop every drip and block re-enrolment",
      operationId: "unsubscribeFromSalesSequences",
      requestBody: {
        content: {
          "application/json": { schema: zodToJsonSchema(unsubscribeFromSalesSequencesSchema) },
        },
      },
    },
  },
  "/api/v1/sequences/{id}": {
    get: { summary: "Get a sequence with its ordered steps", operationId: "getSalesSequence" },
    patch: {
      summary: "Update a sequence",
      operationId: "updateSalesSequence",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(updateSalesSequenceSchema) } },
      },
    },
    delete: { summary: "Soft-delete a sequence", operationId: "deleteSalesSequence" },
  },
  "/api/v1/sequences/{id}/restore": {
    post: { summary: "Restore a soft-deleted sequence", operationId: "restoreSalesSequence" },
  },
  "/api/v1/sequences/{id}/steps": {
    put: {
      summary: "Replace the ordered step list",
      operationId: "replaceSalesSequenceSteps",
      requestBody: {
        content: {
          "application/json": { schema: zodToJsonSchema(replaceSalesSequenceStepsSchema) },
        },
      },
    },
  },
  "/api/v1/sequences/{id}/status": {
    post: {
      summary: "Activate, pause, archive or re-draft a sequence",
      operationId: "setSalesSequenceStatus",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(setStatusSchema) } },
      },
    },
  },
  "/api/v1/sequences/{id}/enrollments": {
    get: {
      summary: "Enrollments of one sequence",
      operationId: "listEnrollmentsForSalesSequence",
    },
    post: {
      summary: "Enrol a person (idempotent per person)",
      operationId: "enrollInSalesSequence",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(enrollInSalesSequenceSchema) } },
      },
    },
  },
  "/api/v1/sequences/{id}/stats": {
    get: {
      summary: "Per-enrollment and per-step counters (no opens/clicks in P0)",
      operationId: "getSalesSequenceStats",
    },
  },
}

export { enrollmentListEnvelope, sequenceEnvelope, sequenceListEnvelope }
