import { zValidator } from "@hono/zod-validator"
import { roleInWorkspace, type Session } from "@yourcrm/auth"
import {
  assignInboxItemSchema,
  createUnifiedInboxService,
  inboxItemQuerySchema,
  inboxItemSchema,
  type InboxItemRecord,
  type UnifiedInboxService,
} from "@yourcrm/crm/src/unified-inbox"
import { getDb, writeAudit } from "@yourcrm/database"
import {
  createUnifiedInboxRepository,
  type InboxItemStatePatch,
} from "@yourcrm/database/src/repositories/unified-inbox-repository"
import { PermissionDeniedError } from "@yourcrm/permissions"
import { errorEnvelope, paginatedEnvelopeSchema } from "@yourcrm/validation"
import { Hono } from "hono"
import type { Context } from "hono"
import { z, ZodError } from "zod"
import type { AppEnv } from "../../hono-env"
import { requireSession } from "../../middleware/auth"
import { zodToJsonSchema } from "../../openapi/zod-to-json-schema"

/**
 * Unified Inbox module (spec 15-unified-inbox, P0).
 *
 * Thin HTTP layer only — validation, session, straight into the domain
 * service (`@yourcrm/crm/src/unified-inbox`); `people.ts` is the golden
 * reference for the shape.
 *
 * ITEM IDENTITY. An inbox item is `(channel, sourceId)`: the conversation
 * lives in email / whatsapp / calling, and the inbox never mints an id of its
 * own for it. Hence the two-segment path `/:channel/:sourceId`. The response
 * also carries the flattened `id` (`"<channel>:<sourceId>"`) for UI keys.
 *
 * NO COMPOSER, NO THREAD VIEW. Opening an item links out to the owning
 * module's detail route; this module deliberately exposes no send, no reply
 * and no message list. Those already exist in `/api/v1/email`,
 * `/api/v1/whatsapp` and `/api/v1/calling`, and duplicating them here would
 * fork three sets of business rules.
 *
 * REGISTRY. `routes/modules/index.ts` is generated by `bun run gen:routes`;
 * this agent must not edit or regenerate it, so the integrator's generator
 * run is what mounts `/api/v1/inbox`. The exports below (`basePath`,
 * `createRoutes`, `openApiPaths`) are the contract that generator reads.
 */

export const basePath = "/inbox"

const inboxItemEnvelope = z.object({ data: inboxItemSchema.passthrough() })
const inboxItemListEnvelope = paginatedEnvelopeSchema(inboxItemSchema.passthrough())

export type UnifiedInboxRouteDeps = {
  service?: UnifiedInboxService
}

function defaultService(): UnifiedInboxService {
  const db = getDb()
  const repository = createUnifiedInboxRepository()
  return createUnifiedInboxService({
    store: {
      list: (workspaceId, query) =>
        repository.listItems(db, {
          workspaceId,
          channels: query.channels,
          scope: query.scope,
          ...(query.limit === undefined ? {} : { limit: query.limit }),
          ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
          ...(query.order === undefined ? {} : { order: query.order }),
          ...(query.unread === undefined ? {} : { unread: query.unread }),
          ...(query.archived === undefined ? {} : { archived: query.archived }),
          ...(query.assignment === undefined ? {} : { assignment: query.assignment }),
          ...(query.personId === undefined ? {} : { personId: query.personId }),
          ...(query.companyId === undefined ? {} : { companyId: query.companyId }),
          ...(query.dealId === undefined ? {} : { dealId: query.dealId }),
        }),
      findItem: (workspaceId, channel, sourceId, scope) =>
        repository.findItem(db, workspaceId, channel, sourceId, scope),
      setState: async (workspaceId, channel, sourceId, patch, actorId) => {
        await repository.upsertItemState(
          db,
          workspaceId,
          channel,
          sourceId,
          patch as InboxItemStatePatch,
          actorId,
        )
      },
    },
    audit: async (input) => {
      await writeAudit(db, { ...input, source: input.source ?? "user" })
    },
  })
}

function serviceContextOf(c: Context<AppEnv>) {
  const session = c.get("session") as Session | null
  return {
    workspaceId: session?.workspaceId ?? "",
    actorId: session?.user.id ?? "",
    role: session ? roleInWorkspace(session) : "viewer",
    correlationId: c.get("requestId") as string | undefined,
  }
}

function refOf(c: Context<AppEnv>) {
  return { channel: c.req.param("channel"), sourceId: c.req.param("sourceId") }
}

function mapError(c: Context<AppEnv>, err: unknown) {
  const requestId = c.get("requestId") as string | undefined
  if (err instanceof PermissionDeniedError) {
    return c.json(errorEnvelope("FORBIDDEN", err.message, requestId), 403)
  }
  if (err instanceof ZodError) {
    // A bad channel or a non-uuid source id arrives as a path parameter, so
    // the service's own parse is the validator — surface it as a 400, never
    // as an unhandled 500.
    return c.json(
      errorEnvelope("VALIDATION_ERROR", "Invalid inbox item reference", requestId, err.flatten()),
      400,
    )
  }
  const code = (err as { code?: string }).code
  if (err instanceof Error && code === "NOT_FOUND") {
    return c.json(errorEnvelope("NOT_FOUND", err.message, requestId), 404)
  }
  if (err instanceof Error && code === "VALIDATION_ERROR") {
    return c.json(errorEnvelope("VALIDATION_ERROR", err.message, requestId), 400)
  }
  throw err
}

export function createRoutes(deps: UnifiedInboxRouteDeps = {}) {
  const app = new Hono<AppEnv>()
  // Lazy default wiring: route construction must never touch the database —
  // registry and full-app tests mount every module without a live Postgres.
  let cached: UnifiedInboxService | null = deps.service ?? null
  const service = () => (cached ??= defaultService())

  const respond = async (
    c: Context<AppEnv>,
    run: () => Promise<InboxItemRecord>,
  ): Promise<Response> => {
    try {
      return c.json({ data: await run() })
    } catch (err) {
      return mapError(c, err)
    }
  }

  app.get(
    "/",
    requireSession(),
    zValidator("query", inboxItemQuerySchema, (result, c) => {
      if (!result.success) {
        return c.json(
          errorEnvelope(
            "VALIDATION_ERROR",
            "Invalid query parameters",
            c.req.header("x-request-id") ?? undefined,
            result.error.flatten(),
          ),
          400,
        )
      }
    }),
    async (c) => {
      try {
        return c.json(await service().list(serviceContextOf(c), c.req.valid("query")))
      } catch (err) {
        return mapError(c, err)
      }
    },
  )

  app.get("/:channel/:sourceId", requireSession(), async (c) =>
    respond(c, () => service().get(serviceContextOf(c), refOf(c))),
  )

  app.post(
    "/:channel/:sourceId/assignee",
    requireSession(),
    zValidator("json", assignInboxItemSchema, (result, c) => {
      if (!result.success) {
        return c.json(
          errorEnvelope(
            "VALIDATION_ERROR",
            "Invalid request body",
            c.req.header("x-request-id") ?? undefined,
            result.error.flatten(),
          ),
          400,
        )
      }
    }),
    async (c) =>
      respond(c, () => service().assign(serviceContextOf(c), refOf(c), c.req.valid("json"))),
  )

  app.post("/:channel/:sourceId/assignee/me", requireSession(), async (c) =>
    respond(c, () => service().claim(serviceContextOf(c), refOf(c))),
  )

  app.delete("/:channel/:sourceId/assignee", requireSession(), async (c) =>
    respond(c, () => service().unassign(serviceContextOf(c), refOf(c))),
  )

  app.post("/:channel/:sourceId/read", requireSession(), async (c) =>
    respond(c, () => service().markRead(serviceContextOf(c), refOf(c))),
  )

  app.delete("/:channel/:sourceId/read", requireSession(), async (c) =>
    respond(c, () => service().markUnread(serviceContextOf(c), refOf(c))),
  )

  app.post("/:channel/:sourceId/archive", requireSession(), async (c) =>
    respond(c, () => service().archive(serviceContextOf(c), refOf(c))),
  )

  app.delete("/:channel/:sourceId/archive", requireSession(), async (c) =>
    respond(c, () => service().unarchive(serviceContextOf(c), refOf(c))),
  )

  return app
}

export const openApiPaths = {
  "/api/v1/inbox": {
    get: {
      summary:
        "List the unified inbox stream (email threads, WhatsApp conversations and calls) with channel, unread, assignment and linked-record filters",
      operationId: "listInboxItems",
    },
  },
  "/api/v1/inbox/{channel}/{sourceId}": {
    get: { summary: "Get one inbox item", operationId: "getInboxItem" },
  },
  "/api/v1/inbox/{channel}/{sourceId}/assignee": {
    post: {
      summary: "Assign an inbox conversation to a user",
      operationId: "assignInboxItem",
      requestBody: {
        content: { "application/json": { schema: zodToJsonSchema(assignInboxItemSchema) } },
      },
    },
    delete: { summary: "Unassign an inbox conversation", operationId: "unassignInboxItem" },
  },
  "/api/v1/inbox/{channel}/{sourceId}/assignee/me": {
    post: {
      summary: "Claim an inbox conversation for the calling user",
      operationId: "claimInboxItem",
    },
  },
  "/api/v1/inbox/{channel}/{sourceId}/read": {
    post: { summary: "Mark an inbox item read", operationId: "markInboxItemRead" },
    delete: { summary: "Mark an inbox item unread", operationId: "markInboxItemUnread" },
  },
  "/api/v1/inbox/{channel}/{sourceId}/archive": {
    post: { summary: "Archive an inbox item", operationId: "archiveInboxItem" },
    delete: { summary: "Restore an archived inbox item", operationId: "unarchiveInboxItem" },
  },
}

export { inboxItemEnvelope, inboxItemListEnvelope }
